// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

// Generated by scripts/sysregs/gen_sysreg_headers.py from
// scripts/sysregs/riscv.yaml -- do not edit by hand.
//
// Each struct below is a thin, bit-field-free wrapper around one raw system
// register value plus, when compiling for a matching target architecture,
// `read()`/`write()` accessors implemented with inline asm. No named
// bit-field accessors are generated yet (`fields` is empty for every
// register in the source YAML); re-running the generator after that YAML
// gains field data will add them here without otherwise changing this file.

#pragma once

#include <cstdint>

namespace structo::arch::riscv::sysreg_raw {

/** @brief Raw accessor for the RISC-V `cycle` CSR (address 0xc00; no named fields yet). */
struct cycle {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static cycle read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc00" : "=r"(value));
    return cycle{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc00, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `time` CSR (address 0xc01; no named fields yet). */
struct time {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static time read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc01" : "=r"(value));
    return time{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc01, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `instret` CSR (address 0xc02; no named fields yet). */
struct instret {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static instret read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc02" : "=r"(value));
    return instret{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc02, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter3` CSR (address 0xc03; no named fields yet). */
struct hpmcounter3 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter3 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc03" : "=r"(value));
    return hpmcounter3{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc03, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter4` CSR (address 0xc04; no named fields yet). */
struct hpmcounter4 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter4 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc04" : "=r"(value));
    return hpmcounter4{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc04, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter5` CSR (address 0xc05; no named fields yet). */
struct hpmcounter5 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter5 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc05" : "=r"(value));
    return hpmcounter5{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc05, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter6` CSR (address 0xc06; no named fields yet). */
struct hpmcounter6 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter6 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc06" : "=r"(value));
    return hpmcounter6{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc06, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter7` CSR (address 0xc07; no named fields yet). */
struct hpmcounter7 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter7 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc07" : "=r"(value));
    return hpmcounter7{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc07, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter8` CSR (address 0xc08; no named fields yet). */
struct hpmcounter8 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter8 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc08" : "=r"(value));
    return hpmcounter8{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc08, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter9` CSR (address 0xc09; no named fields yet). */
struct hpmcounter9 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter9 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc09" : "=r"(value));
    return hpmcounter9{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc09, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter10` CSR (address 0xc0a; no named fields yet). */
struct hpmcounter10 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter10 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc0a" : "=r"(value));
    return hpmcounter10{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc0a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter11` CSR (address 0xc0b; no named fields yet). */
struct hpmcounter11 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter11 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc0b" : "=r"(value));
    return hpmcounter11{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc0b, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter12` CSR (address 0xc0c; no named fields yet). */
struct hpmcounter12 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter12 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc0c" : "=r"(value));
    return hpmcounter12{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc0c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter13` CSR (address 0xc0d; no named fields yet). */
struct hpmcounter13 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter13 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc0d" : "=r"(value));
    return hpmcounter13{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc0d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter14` CSR (address 0xc0e; no named fields yet). */
struct hpmcounter14 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter14 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc0e" : "=r"(value));
    return hpmcounter14{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc0e, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter15` CSR (address 0xc0f; no named fields yet). */
struct hpmcounter15 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter15 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc0f" : "=r"(value));
    return hpmcounter15{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc0f, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter16` CSR (address 0xc10; no named fields yet). */
struct hpmcounter16 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter16 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc10" : "=r"(value));
    return hpmcounter16{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc10, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter17` CSR (address 0xc11; no named fields yet). */
struct hpmcounter17 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter17 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc11" : "=r"(value));
    return hpmcounter17{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc11, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter18` CSR (address 0xc12; no named fields yet). */
struct hpmcounter18 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter18 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc12" : "=r"(value));
    return hpmcounter18{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc12, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter19` CSR (address 0xc13; no named fields yet). */
struct hpmcounter19 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter19 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc13" : "=r"(value));
    return hpmcounter19{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc13, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter20` CSR (address 0xc14; no named fields yet). */
struct hpmcounter20 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter20 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc14" : "=r"(value));
    return hpmcounter20{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc14, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter21` CSR (address 0xc15; no named fields yet). */
struct hpmcounter21 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter21 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc15" : "=r"(value));
    return hpmcounter21{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc15, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter22` CSR (address 0xc16; no named fields yet). */
struct hpmcounter22 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter22 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc16" : "=r"(value));
    return hpmcounter22{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc16, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter23` CSR (address 0xc17; no named fields yet). */
struct hpmcounter23 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter23 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc17" : "=r"(value));
    return hpmcounter23{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc17, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter24` CSR (address 0xc18; no named fields yet). */
struct hpmcounter24 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter24 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc18" : "=r"(value));
    return hpmcounter24{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc18, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter25` CSR (address 0xc19; no named fields yet). */
struct hpmcounter25 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter25 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc19" : "=r"(value));
    return hpmcounter25{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc19, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter26` CSR (address 0xc1a; no named fields yet). */
struct hpmcounter26 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter26 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc1a" : "=r"(value));
    return hpmcounter26{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc1a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter27` CSR (address 0xc1b; no named fields yet). */
struct hpmcounter27 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter27 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc1b" : "=r"(value));
    return hpmcounter27{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc1b, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter28` CSR (address 0xc1c; no named fields yet). */
struct hpmcounter28 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter28 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc1c" : "=r"(value));
    return hpmcounter28{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc1c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter29` CSR (address 0xc1d; no named fields yet). */
struct hpmcounter29 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter29 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc1d" : "=r"(value));
    return hpmcounter29{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc1d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter30` CSR (address 0xc1e; no named fields yet). */
struct hpmcounter30 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter30 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc1e" : "=r"(value));
    return hpmcounter30{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc1e, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter31` CSR (address 0xc1f; no named fields yet). */
struct hpmcounter31 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter31 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc1f" : "=r"(value));
    return hpmcounter31{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc1f, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `cycleh` CSR (address 0xc80; no named fields yet). */
struct cycleh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static cycleh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc80" : "=r"(value));
    return cycleh{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc80, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `timeh` CSR (address 0xc81; no named fields yet). */
struct timeh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static timeh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc81" : "=r"(value));
    return timeh{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc81, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `instreth` CSR (address 0xc82; no named fields yet). */
struct instreth {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static instreth read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc82" : "=r"(value));
    return instreth{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc82, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter3_h` CSR (address 0xc83; no named fields yet). */
struct hpmcounter3_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter3_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc83" : "=r"(value));
    return hpmcounter3_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc83, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter4_h` CSR (address 0xc84; no named fields yet). */
struct hpmcounter4_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter4_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc84" : "=r"(value));
    return hpmcounter4_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc84, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter5_h` CSR (address 0xc85; no named fields yet). */
struct hpmcounter5_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter5_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc85" : "=r"(value));
    return hpmcounter5_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc85, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter6_h` CSR (address 0xc86; no named fields yet). */
struct hpmcounter6_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter6_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc86" : "=r"(value));
    return hpmcounter6_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc86, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter7_h` CSR (address 0xc87; no named fields yet). */
struct hpmcounter7_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter7_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc87" : "=r"(value));
    return hpmcounter7_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc87, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter8_h` CSR (address 0xc88; no named fields yet). */
struct hpmcounter8_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter8_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc88" : "=r"(value));
    return hpmcounter8_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc88, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter9_h` CSR (address 0xc89; no named fields yet). */
struct hpmcounter9_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter9_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc89" : "=r"(value));
    return hpmcounter9_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc89, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter10_h` CSR (address 0xc8a; no named fields yet). */
struct hpmcounter10_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter10_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc8a" : "=r"(value));
    return hpmcounter10_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc8a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter11_h` CSR (address 0xc8b; no named fields yet). */
struct hpmcounter11_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter11_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc8b" : "=r"(value));
    return hpmcounter11_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc8b, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter12_h` CSR (address 0xc8c; no named fields yet). */
struct hpmcounter12_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter12_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc8c" : "=r"(value));
    return hpmcounter12_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc8c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter13_h` CSR (address 0xc8d; no named fields yet). */
struct hpmcounter13_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter13_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc8d" : "=r"(value));
    return hpmcounter13_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc8d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter14_h` CSR (address 0xc8e; no named fields yet). */
struct hpmcounter14_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter14_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc8e" : "=r"(value));
    return hpmcounter14_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc8e, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter15_h` CSR (address 0xc8f; no named fields yet). */
struct hpmcounter15_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter15_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc8f" : "=r"(value));
    return hpmcounter15_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc8f, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter16_h` CSR (address 0xc90; no named fields yet). */
struct hpmcounter16_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter16_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc90" : "=r"(value));
    return hpmcounter16_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc90, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter17_h` CSR (address 0xc91; no named fields yet). */
struct hpmcounter17_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter17_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc91" : "=r"(value));
    return hpmcounter17_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc91, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter18_h` CSR (address 0xc92; no named fields yet). */
struct hpmcounter18_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter18_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc92" : "=r"(value));
    return hpmcounter18_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc92, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter19_h` CSR (address 0xc93; no named fields yet). */
struct hpmcounter19_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter19_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc93" : "=r"(value));
    return hpmcounter19_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc93, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter20_h` CSR (address 0xc94; no named fields yet). */
struct hpmcounter20_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter20_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc94" : "=r"(value));
    return hpmcounter20_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc94, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter21_h` CSR (address 0xc95; no named fields yet). */
struct hpmcounter21_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter21_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc95" : "=r"(value));
    return hpmcounter21_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc95, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter22_h` CSR (address 0xc96; no named fields yet). */
struct hpmcounter22_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter22_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc96" : "=r"(value));
    return hpmcounter22_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc96, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter23_h` CSR (address 0xc97; no named fields yet). */
struct hpmcounter23_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter23_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc97" : "=r"(value));
    return hpmcounter23_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc97, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter24_h` CSR (address 0xc98; no named fields yet). */
struct hpmcounter24_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter24_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc98" : "=r"(value));
    return hpmcounter24_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc98, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter25_h` CSR (address 0xc99; no named fields yet). */
struct hpmcounter25_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter25_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc99" : "=r"(value));
    return hpmcounter25_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc99, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter26_h` CSR (address 0xc9a; no named fields yet). */
struct hpmcounter26_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter26_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc9a" : "=r"(value));
    return hpmcounter26_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc9a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter27_h` CSR (address 0xc9b; no named fields yet). */
struct hpmcounter27_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter27_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc9b" : "=r"(value));
    return hpmcounter27_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc9b, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter28_h` CSR (address 0xc9c; no named fields yet). */
struct hpmcounter28_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter28_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc9c" : "=r"(value));
    return hpmcounter28_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc9c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter29_h` CSR (address 0xc9d; no named fields yet). */
struct hpmcounter29_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter29_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc9d" : "=r"(value));
    return hpmcounter29_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc9d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter30_h` CSR (address 0xc9e; no named fields yet). */
struct hpmcounter30_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter30_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc9e" : "=r"(value));
    return hpmcounter30_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc9e, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hpmcounter31_h` CSR (address 0xc9f; no named fields yet). */
struct hpmcounter31_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hpmcounter31_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc9f" : "=r"(value));
    return hpmcounter31_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc9f, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sscountovf` CSR (address 0xda0; no named fields yet). */
struct sscountovf {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sscountovf read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xda0" : "=r"(value));
    return sscountovf{value};
  }
  void write() const noexcept { asm volatile("csrw 0xda0, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sstatus` CSR (address 0x100; no named fields yet). */
struct sstatus {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sstatus read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x100" : "=r"(value));
    return sstatus{value};
  }
  void write() const noexcept { asm volatile("csrw 0x100, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sie` CSR (address 0x104; no named fields yet). */
struct sie {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sie read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x104" : "=r"(value));
    return sie{value};
  }
  void write() const noexcept { asm volatile("csrw 0x104, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `stvec` CSR (address 0x105; no named fields yet). */
struct stvec {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static stvec read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x105" : "=r"(value));
    return stvec{value};
  }
  void write() const noexcept { asm volatile("csrw 0x105, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `scounteren` CSR (address 0x106; no named fields yet). */
struct scounteren {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static scounteren read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x106" : "=r"(value));
    return scounteren{value};
  }
  void write() const noexcept { asm volatile("csrw 0x106, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `senvcfg` CSR (address 0x10a; no named fields yet). */
struct senvcfg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static senvcfg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x10a" : "=r"(value));
    return senvcfg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x10a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sstateen0` CSR (address 0x10c; no named fields yet). */
struct sstateen0 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sstateen0 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x10c" : "=r"(value));
    return sstateen0{value};
  }
  void write() const noexcept { asm volatile("csrw 0x10c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sscratch` CSR (address 0x140; no named fields yet). */
struct sscratch {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sscratch read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x140" : "=r"(value));
    return sscratch{value};
  }
  void write() const noexcept { asm volatile("csrw 0x140, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sepc` CSR (address 0x141; no named fields yet). */
struct sepc {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sepc read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x141" : "=r"(value));
    return sepc{value};
  }
  void write() const noexcept { asm volatile("csrw 0x141, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `scause` CSR (address 0x142; no named fields yet). */
struct scause {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static scause read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x142" : "=r"(value));
    return scause{value};
  }
  void write() const noexcept { asm volatile("csrw 0x142, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `stval` CSR (address 0x143; no named fields yet). */
struct stval {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static stval read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x143" : "=r"(value));
    return stval{value};
  }
  void write() const noexcept { asm volatile("csrw 0x143, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sip` CSR (address 0x144; no named fields yet). */
struct sip {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sip read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x144" : "=r"(value));
    return sip{value};
  }
  void write() const noexcept { asm volatile("csrw 0x144, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `satp` CSR (address 0x180; no named fields yet). */
struct satp {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static satp read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x180" : "=r"(value));
    return satp{value};
  }
  void write() const noexcept { asm volatile("csrw 0x180, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `stimecmp` CSR (address 0x14d; no named fields yet). */
struct stimecmp {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static stimecmp read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x14d" : "=r"(value));
    return stimecmp{value};
  }
  void write() const noexcept { asm volatile("csrw 0x14d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `stimecmph` CSR (address 0x15d; no named fields yet). */
struct stimecmph {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static stimecmph read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x15d" : "=r"(value));
    return stimecmph{value};
  }
  void write() const noexcept { asm volatile("csrw 0x15d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `siselect` CSR (address 0x150; no named fields yet). */
struct siselect {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static siselect read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x150" : "=r"(value));
    return siselect{value};
  }
  void write() const noexcept { asm volatile("csrw 0x150, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sireg` CSR (address 0x151; no named fields yet). */
struct sireg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sireg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x151" : "=r"(value));
    return sireg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x151, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `stopei` CSR (address 0x15c; no named fields yet). */
struct stopei {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static stopei read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x15c" : "=r"(value));
    return stopei{value};
  }
  void write() const noexcept { asm volatile("csrw 0x15c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `stopi` CSR (address 0xdb0; no named fields yet). */
struct stopi {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static stopi read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xdb0" : "=r"(value));
    return stopi{value};
  }
  void write() const noexcept { asm volatile("csrw 0xdb0, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `sieh` CSR (address 0x114; no named fields yet). */
struct sieh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static sieh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x114" : "=r"(value));
    return sieh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x114, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `siph` CSR (address 0x154; no named fields yet). */
struct siph {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static siph read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x154" : "=r"(value));
    return siph{value};
  }
  void write() const noexcept { asm volatile("csrw 0x154, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsstatus` CSR (address 0x200; no named fields yet). */
struct vsstatus {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsstatus read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x200" : "=r"(value));
    return vsstatus{value};
  }
  void write() const noexcept { asm volatile("csrw 0x200, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsie` CSR (address 0x204; no named fields yet). */
struct vsie {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsie read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x204" : "=r"(value));
    return vsie{value};
  }
  void write() const noexcept { asm volatile("csrw 0x204, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vstvec` CSR (address 0x205; no named fields yet). */
struct vstvec {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vstvec read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x205" : "=r"(value));
    return vstvec{value};
  }
  void write() const noexcept { asm volatile("csrw 0x205, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsscratch` CSR (address 0x240; no named fields yet). */
struct vsscratch {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsscratch read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x240" : "=r"(value));
    return vsscratch{value};
  }
  void write() const noexcept { asm volatile("csrw 0x240, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsepc` CSR (address 0x241; no named fields yet). */
struct vsepc {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsepc read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x241" : "=r"(value));
    return vsepc{value};
  }
  void write() const noexcept { asm volatile("csrw 0x241, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vscause` CSR (address 0x242; no named fields yet). */
struct vscause {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vscause read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x242" : "=r"(value));
    return vscause{value};
  }
  void write() const noexcept { asm volatile("csrw 0x242, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vstval` CSR (address 0x243; no named fields yet). */
struct vstval {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vstval read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x243" : "=r"(value));
    return vstval{value};
  }
  void write() const noexcept { asm volatile("csrw 0x243, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsip` CSR (address 0x244; no named fields yet). */
struct vsip {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsip read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x244" : "=r"(value));
    return vsip{value};
  }
  void write() const noexcept { asm volatile("csrw 0x244, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsatp` CSR (address 0x280; no named fields yet). */
struct vsatp {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsatp read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x280" : "=r"(value));
    return vsatp{value};
  }
  void write() const noexcept { asm volatile("csrw 0x280, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vstimecmp` CSR (address 0x24d; no named fields yet). */
struct vstimecmp {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vstimecmp read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x24d" : "=r"(value));
    return vstimecmp{value};
  }
  void write() const noexcept { asm volatile("csrw 0x24d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vstimecmph` CSR (address 0x25d; no named fields yet). */
struct vstimecmph {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vstimecmph read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x25d" : "=r"(value));
    return vstimecmph{value};
  }
  void write() const noexcept { asm volatile("csrw 0x25d, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hstatus` CSR (address 0x600; no named fields yet). */
struct hstatus {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hstatus read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x600" : "=r"(value));
    return hstatus{value};
  }
  void write() const noexcept { asm volatile("csrw 0x600, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hedeleg` CSR (address 0x602; no named fields yet). */
struct hedeleg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hedeleg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x602" : "=r"(value));
    return hedeleg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x602, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hideleg` CSR (address 0x603; no named fields yet). */
struct hideleg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hideleg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x603" : "=r"(value));
    return hideleg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x603, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hie` CSR (address 0x604; no named fields yet). */
struct hie {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hie read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x604" : "=r"(value));
    return hie{value};
  }
  void write() const noexcept { asm volatile("csrw 0x604, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `htimedelta` CSR (address 0x605; no named fields yet). */
struct htimedelta {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static htimedelta read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x605" : "=r"(value));
    return htimedelta{value};
  }
  void write() const noexcept { asm volatile("csrw 0x605, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hcounteren` CSR (address 0x606; no named fields yet). */
struct hcounteren {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hcounteren read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x606" : "=r"(value));
    return hcounteren{value};
  }
  void write() const noexcept { asm volatile("csrw 0x606, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hgeie` CSR (address 0x607; no named fields yet). */
struct hgeie {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hgeie read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x607" : "=r"(value));
    return hgeie{value};
  }
  void write() const noexcept { asm volatile("csrw 0x607, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `henvcfg` CSR (address 0x60a; no named fields yet). */
struct henvcfg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static henvcfg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x60a" : "=r"(value));
    return henvcfg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x60a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `htimedeltah` CSR (address 0x615; no named fields yet). */
struct htimedeltah {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static htimedeltah read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x615" : "=r"(value));
    return htimedeltah{value};
  }
  void write() const noexcept { asm volatile("csrw 0x615, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `henvcfgh` CSR (address 0x61a; no named fields yet). */
struct henvcfgh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static henvcfgh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x61a" : "=r"(value));
    return henvcfgh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x61a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `htval` CSR (address 0x643; no named fields yet). */
struct htval {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static htval read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x643" : "=r"(value));
    return htval{value};
  }
  void write() const noexcept { asm volatile("csrw 0x643, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hip` CSR (address 0x644; no named fields yet). */
struct hip {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hip read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x644" : "=r"(value));
    return hip{value};
  }
  void write() const noexcept { asm volatile("csrw 0x644, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hvip` CSR (address 0x645; no named fields yet). */
struct hvip {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hvip read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x645" : "=r"(value));
    return hvip{value};
  }
  void write() const noexcept { asm volatile("csrw 0x645, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `htinst` CSR (address 0x64a; no named fields yet). */
struct htinst {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static htinst read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x64a" : "=r"(value));
    return htinst{value};
  }
  void write() const noexcept { asm volatile("csrw 0x64a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hgatp` CSR (address 0x680; no named fields yet). */
struct hgatp {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hgatp read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x680" : "=r"(value));
    return hgatp{value};
  }
  void write() const noexcept { asm volatile("csrw 0x680, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hgeip` CSR (address 0xe12; no named fields yet). */
struct hgeip {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hgeip read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xe12" : "=r"(value));
    return hgeip{value};
  }
  void write() const noexcept { asm volatile("csrw 0xe12, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hvien` CSR (address 0x608; no named fields yet). */
struct hvien {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hvien read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x608" : "=r"(value));
    return hvien{value};
  }
  void write() const noexcept { asm volatile("csrw 0x608, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hvictl` CSR (address 0x609; no named fields yet). */
struct hvictl {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hvictl read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x609" : "=r"(value));
    return hvictl{value};
  }
  void write() const noexcept { asm volatile("csrw 0x609, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hviprio1` CSR (address 0x646; no named fields yet). */
struct hviprio1 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hviprio1 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x646" : "=r"(value));
    return hviprio1{value};
  }
  void write() const noexcept { asm volatile("csrw 0x646, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hviprio2` CSR (address 0x647; no named fields yet). */
struct hviprio2 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hviprio2 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x647" : "=r"(value));
    return hviprio2{value};
  }
  void write() const noexcept { asm volatile("csrw 0x647, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsiselect` CSR (address 0x250; no named fields yet). */
struct vsiselect {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsiselect read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x250" : "=r"(value));
    return vsiselect{value};
  }
  void write() const noexcept { asm volatile("csrw 0x250, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsireg` CSR (address 0x251; no named fields yet). */
struct vsireg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsireg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x251" : "=r"(value));
    return vsireg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x251, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vstopei` CSR (address 0x25c; no named fields yet). */
struct vstopei {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vstopei read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x25c" : "=r"(value));
    return vstopei{value};
  }
  void write() const noexcept { asm volatile("csrw 0x25c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vstopi` CSR (address 0xeb0; no named fields yet). */
struct vstopi {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vstopi read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xeb0" : "=r"(value));
    return vstopi{value};
  }
  void write() const noexcept { asm volatile("csrw 0xeb0, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hidelegh` CSR (address 0x613; no named fields yet). */
struct hidelegh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hidelegh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x613" : "=r"(value));
    return hidelegh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x613, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hvienh` CSR (address 0x618; no named fields yet). */
struct hvienh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hvienh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x618" : "=r"(value));
    return hvienh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x618, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hviph` CSR (address 0x655; no named fields yet). */
struct hviph {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hviph read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x655" : "=r"(value));
    return hviph{value};
  }
  void write() const noexcept { asm volatile("csrw 0x655, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hviprio1_h` CSR (address 0x656; no named fields yet). */
struct hviprio1_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hviprio1_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x656" : "=r"(value));
    return hviprio1_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0x656, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hviprio2_h` CSR (address 0x657; no named fields yet). */
struct hviprio2_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hviprio2_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x657" : "=r"(value));
    return hviprio2_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0x657, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsieh` CSR (address 0x214; no named fields yet). */
struct vsieh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsieh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x214" : "=r"(value));
    return vsieh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x214, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vsiph` CSR (address 0x254; no named fields yet). */
struct vsiph {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vsiph read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x254" : "=r"(value));
    return vsiph{value};
  }
  void write() const noexcept { asm volatile("csrw 0x254, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hstateen0` CSR (address 0x60c; no named fields yet). */
struct hstateen0 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hstateen0 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x60c" : "=r"(value));
    return hstateen0{value};
  }
  void write() const noexcept { asm volatile("csrw 0x60c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `hstateen0_h` CSR (address 0x61c; no named fields yet). */
struct hstateen0_h {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static hstateen0_h read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x61c" : "=r"(value));
    return hstateen0_h{value};
  }
  void write() const noexcept { asm volatile("csrw 0x61c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mstatus` CSR (address 0x300; no named fields yet). */
struct mstatus {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mstatus read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x300" : "=r"(value));
    return mstatus{value};
  }
  void write() const noexcept { asm volatile("csrw 0x300, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `misa` CSR (address 0x301; no named fields yet). */
struct misa {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static misa read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x301" : "=r"(value));
    return misa{value};
  }
  void write() const noexcept { asm volatile("csrw 0x301, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mideleg` CSR (address 0x303; no named fields yet). */
struct mideleg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mideleg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x303" : "=r"(value));
    return mideleg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x303, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mie` CSR (address 0x304; no named fields yet). */
struct mie {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mie read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x304" : "=r"(value));
    return mie{value};
  }
  void write() const noexcept { asm volatile("csrw 0x304, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mtvec` CSR (address 0x305; no named fields yet). */
struct mtvec {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mtvec read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x305" : "=r"(value));
    return mtvec{value};
  }
  void write() const noexcept { asm volatile("csrw 0x305, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `menvcfg` CSR (address 0x30a; no named fields yet). */
struct menvcfg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static menvcfg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x30a" : "=r"(value));
    return menvcfg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x30a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `menvcfgh` CSR (address 0x31a; no named fields yet). */
struct menvcfgh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static menvcfgh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x31a" : "=r"(value));
    return menvcfgh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x31a, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mscratch` CSR (address 0x340; no named fields yet). */
struct mscratch {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mscratch read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x340" : "=r"(value));
    return mscratch{value};
  }
  void write() const noexcept { asm volatile("csrw 0x340, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mepc` CSR (address 0x341; no named fields yet). */
struct mepc {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mepc read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x341" : "=r"(value));
    return mepc{value};
  }
  void write() const noexcept { asm volatile("csrw 0x341, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mcause` CSR (address 0x342; no named fields yet). */
struct mcause {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mcause read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x342" : "=r"(value));
    return mcause{value};
  }
  void write() const noexcept { asm volatile("csrw 0x342, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mtval` CSR (address 0x343; no named fields yet). */
struct mtval {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mtval read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x343" : "=r"(value));
    return mtval{value};
  }
  void write() const noexcept { asm volatile("csrw 0x343, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mip` CSR (address 0x344; no named fields yet). */
struct mip {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mip read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x344" : "=r"(value));
    return mip{value};
  }
  void write() const noexcept { asm volatile("csrw 0x344, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `pmpcfg0` CSR (address 0x3a0; no named fields yet). */
struct pmpcfg0 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static pmpcfg0 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x3a0" : "=r"(value));
    return pmpcfg0{value};
  }
  void write() const noexcept { asm volatile("csrw 0x3a0, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `pmpaddr0` CSR (address 0x3b0; no named fields yet). */
struct pmpaddr0 {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static pmpaddr0 read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x3b0" : "=r"(value));
    return pmpaddr0{value};
  }
  void write() const noexcept { asm volatile("csrw 0x3b0, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mvendorid` CSR (address 0xf11; no named fields yet). */
struct mvendorid {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mvendorid read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xf11" : "=r"(value));
    return mvendorid{value};
  }
  void write() const noexcept { asm volatile("csrw 0xf11, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `marchid` CSR (address 0xf12; no named fields yet). */
struct marchid {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static marchid read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xf12" : "=r"(value));
    return marchid{value};
  }
  void write() const noexcept { asm volatile("csrw 0xf12, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mimpid` CSR (address 0xf13; no named fields yet). */
struct mimpid {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mimpid read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xf13" : "=r"(value));
    return mimpid{value};
  }
  void write() const noexcept { asm volatile("csrw 0xf13, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mhartid` CSR (address 0xf14; no named fields yet). */
struct mhartid {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mhartid read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xf14" : "=r"(value));
    return mhartid{value};
  }
  void write() const noexcept { asm volatile("csrw 0xf14, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `miselect` CSR (address 0x350; no named fields yet). */
struct miselect {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static miselect read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x350" : "=r"(value));
    return miselect{value};
  }
  void write() const noexcept { asm volatile("csrw 0x350, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mireg` CSR (address 0x351; no named fields yet). */
struct mireg {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mireg read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x351" : "=r"(value));
    return mireg{value};
  }
  void write() const noexcept { asm volatile("csrw 0x351, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mtopei` CSR (address 0x35c; no named fields yet). */
struct mtopei {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mtopei read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x35c" : "=r"(value));
    return mtopei{value};
  }
  void write() const noexcept { asm volatile("csrw 0x35c, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mtopi` CSR (address 0xfb0; no named fields yet). */
struct mtopi {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mtopi read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xfb0" : "=r"(value));
    return mtopi{value};
  }
  void write() const noexcept { asm volatile("csrw 0xfb0, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mvien` CSR (address 0x308; no named fields yet). */
struct mvien {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mvien read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x308" : "=r"(value));
    return mvien{value};
  }
  void write() const noexcept { asm volatile("csrw 0x308, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mvip` CSR (address 0x309; no named fields yet). */
struct mvip {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mvip read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x309" : "=r"(value));
    return mvip{value};
  }
  void write() const noexcept { asm volatile("csrw 0x309, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `midelegh` CSR (address 0x313; no named fields yet). */
struct midelegh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static midelegh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x313" : "=r"(value));
    return midelegh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x313, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mieh` CSR (address 0x314; no named fields yet). */
struct mieh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mieh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x314" : "=r"(value));
    return mieh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x314, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mvienh` CSR (address 0x318; no named fields yet). */
struct mvienh {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mvienh read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x318" : "=r"(value));
    return mvienh{value};
  }
  void write() const noexcept { asm volatile("csrw 0x318, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `mviph` CSR (address 0x319; no named fields yet). */
struct mviph {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static mviph read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x319" : "=r"(value));
    return mviph{value};
  }
  void write() const noexcept { asm volatile("csrw 0x319, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `miph` CSR (address 0x354; no named fields yet). */
struct miph {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static miph read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x354" : "=r"(value));
    return miph{value};
  }
  void write() const noexcept { asm volatile("csrw 0x354, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vstart` CSR (address 0x8; no named fields yet). */
struct vstart {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vstart read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x8" : "=r"(value));
    return vstart{value};
  }
  void write() const noexcept { asm volatile("csrw 0x8, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vcsr` CSR (address 0xf; no named fields yet). */
struct vcsr {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vcsr read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xf" : "=r"(value));
    return vcsr{value};
  }
  void write() const noexcept { asm volatile("csrw 0xf, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vl` CSR (address 0xc20; no named fields yet). */
struct vl {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vl read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc20" : "=r"(value));
    return vl{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc20, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vtype` CSR (address 0xc21; no named fields yet). */
struct vtype {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vtype read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc21" : "=r"(value));
    return vtype{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc21, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `vlenb` CSR (address 0xc22; no named fields yet). */
struct vlenb {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static vlenb read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0xc22" : "=r"(value));
    return vlenb{value};
  }
  void write() const noexcept { asm volatile("csrw 0xc22, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

/** @brief Raw accessor for the RISC-V `seed` CSR (address 0x15; no named fields yet). */
struct seed {
  unsigned long raw{0};

#if defined(__riscv)
  [[nodiscard]] static seed read() noexcept {
    unsigned long value;
    asm volatile("csrr %0, 0x15" : "=r"(value));
    return seed{value};
  }
  void write() const noexcept { asm volatile("csrw 0x15, %0" ::"r"(raw)); }
#endif // defined(__riscv)
};

} // namespace structo::arch::riscv::sysreg_raw
