// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

// Exercises the two example fonts generated by
// scripts/ttf_to_font_header.py from DejaVu Sans Mono
// (examples/fonts/dejavu_sans_mono_8x*_font.hpp) as a `Font` plugged
// into `framebuffer_console`, confirming the generator's output is a
// genuine drop-in replacement for `block_font_8x8`.

#include <gtest/gtest.h>
#include <structo/hw/framebuffer_console.hpp>

#include "fonts/dejavu_sans_mono_8x16_font.hpp"
#include "fonts/dejavu_sans_mono_8x8_font.hpp"

using namespace structo::hw;
using structo::examples::fonts::dejavu_sans_mono_8x16;
using structo::examples::fonts::dejavu_sans_mono_8x8;

namespace {

rgb_color px(const framebuffer<xrgb8888> &fb, std::size_t x, std::size_t y) {
  auto r = fb.get_pixel(x, y);
  return *r;
}

template <typename Font> void exercise_font() {
  constexpr std::size_t kFbWidth = Font::glyph_width * 2;
  constexpr std::size_t kFbHeight = Font::glyph_height * 2;
  std::byte fb_storage[kFbWidth * kFbHeight * 4]{};
  auto fb = framebuffer<xrgb8888>::try_create(reloco::span<std::byte>(fb_storage, sizeof(fb_storage)), kFbWidth,
                                              kFbHeight, kFbWidth * 4);
  ASSERT_TRUE(fb);

  console_cell cell_storage[2 * 2]{};
  auto console = framebuffer_console<xrgb8888, Font>::try_create(*fb, reloco::span<console_cell>(cell_storage, 4));
  ASSERT_TRUE(console);

  // 'A' is a dense glyph (every row of block_font_8x8 would be solid);
  // for a real font it must *not* fill every pixel, proving actual
  // glyph shape data -- not a block placeholder -- was rasterized.
  console->put_cell(0, 0, 'A', console_color::white, console_color::black);
  EXPECT_EQ(console->get_cell(0, 0).ch, 'A');

  std::size_t lit = 0;
  for (std::size_t y = 0; y < Font::glyph_height; ++y) {
    for (std::size_t x = 0; x < Font::glyph_width; ++x) {
      rgb_color c = px(*fb, x, y);
      if (c.r != 0 || c.g != 0 || c.b != 0)
        ++lit;
    }
  }
  EXPECT_GT(lit, 0u);
  EXPECT_LT(lit, Font::glyph_width * Font::glyph_height);

  // A space must stay fully blank.
  console->put_cell(1, 1, ' ', console_color::white, console_color::black);
  for (std::size_t y = 0; y < Font::glyph_height; ++y) {
    for (std::size_t x = 0; x < Font::glyph_width; ++x) {
      rgb_color c = px(*fb, Font::glyph_width + x, Font::glyph_height + y);
      EXPECT_EQ(c.r, 0u);
      EXPECT_EQ(c.g, 0u);
      EXPECT_EQ(c.b, 0u);
    }
  }
}

} // namespace

TEST(DejavuFontTest, Glyph8x16RendersRealShapeNotABlock) { exercise_font<dejavu_sans_mono_8x16>(); }

TEST(DejavuFontTest, Glyph8x8RendersRealShapeNotABlock) { exercise_font<dejavu_sans_mono_8x8>(); }
