// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

// Exercises the two example fonts generated by
// scripts/ttf_to_font_header.py from DejaVu Sans Mono
// (examples/fonts/dejavu_sans_mono_8x*_font.hpp) as a `Font` plugged
// into `framebuffer_console`, confirming the generator's output is a
// genuine drop-in replacement for `block_font_8x8`.

#include <gtest/gtest.h>
#include <cstring>
#include <structo/hw/framebuffer_console.hpp>

#include "fonts/all_fonts.hpp"
#include "fonts/dejavu_sans_mono_8x16_font.hpp"
#include "fonts/dejavu_sans_mono_8x8_font.hpp"

using namespace structo::hw;
using structo::examples::fonts::dejavu_sans_mono_8x16;
using structo::examples::fonts::dejavu_sans_mono_8x8;

namespace {

rgb_color px(const framebuffer<xrgb8888> &fb, std::size_t x, std::size_t y) {
  auto r = fb.get_pixel(x, y);
  return *r;
}

template <typename Font> void exercise_font() {
  constexpr std::size_t kFbWidth = Font::glyph_width * 2;
  constexpr std::size_t kFbHeight = Font::glyph_height * 2;
  std::byte fb_storage[kFbWidth * kFbHeight * 4]{};
  auto fb = framebuffer<xrgb8888>::try_create(reloco::span<std::byte>(fb_storage, sizeof(fb_storage)), kFbWidth,
                                              kFbHeight, kFbWidth * 4);
  ASSERT_TRUE(fb);

  console_cell cell_storage[2 * 2]{};
  auto console = framebuffer_console<xrgb8888, Font>::try_create(*fb, reloco::span<console_cell>(cell_storage, 4));
  ASSERT_TRUE(console);

  // 'A' is a dense glyph (every row of block_font_8x8 would be solid);
  // for a real font it must *not* fill every pixel, proving actual
  // glyph shape data -- not a block placeholder -- was rasterized.
  console->put_cell(0, 0, 'A', console_color::white, console_color::black);
  EXPECT_EQ(console->get_cell(0, 0).ch, 'A');

  std::size_t lit = 0;
  for (std::size_t y = 0; y < Font::glyph_height; ++y) {
    for (std::size_t x = 0; x < Font::glyph_width; ++x) {
      rgb_color c = px(*fb, x, y);
      if (c.r != 0 || c.g != 0 || c.b != 0)
        ++lit;
    }
  }
  EXPECT_GT(lit, 0u);
  EXPECT_LT(lit, Font::glyph_width * Font::glyph_height);

  // A space must stay fully blank.
  console->put_cell(1, 1, ' ', console_color::white, console_color::black);
  for (std::size_t y = 0; y < Font::glyph_height; ++y) {
    for (std::size_t x = 0; x < Font::glyph_width; ++x) {
      rgb_color c = px(*fb, Font::glyph_width + x, Font::glyph_height + y);
      EXPECT_EQ(c.r, 0u);
      EXPECT_EQ(c.g, 0u);
      EXPECT_EQ(c.b, 0u);
    }
  }
}

} // namespace

TEST(DejavuFontTest, Glyph8x16RendersRealShapeNotABlock) { exercise_font<dejavu_sans_mono_8x16>(); }

TEST(DejavuFontTest, Glyph8x8RendersRealShapeNotABlock) { exercise_font<dejavu_sans_mono_8x8>(); }

namespace {

template <typename Font> void expect_sane_bitmap_font() {
  auto ink = [](const std::uint8_t *g) {
    unsigned bits = 0;
    for (std::size_t y = 0; y < Font::glyph_height; ++y)
      bits |= g[y];
    return bits;
  };
  EXPECT_EQ(ink(Font::glyph_bitmap(' ')), 0u);        // space has no ink
  EXPECT_EQ(ink(Font::glyph_bitmap('\x01')), 0u);     // outside 0x20..0x7E is blank
  EXPECT_NE(ink(Font::glyph_bitmap('A')), 0u);
  EXPECT_NE(ink(Font::glyph_bitmap('~')), 0u);
  EXPECT_NE(Font::glyph_bitmap('A')[0] | Font::glyph_bitmap('A')[Font::glyph_height / 2], 0u);
  EXPECT_NE(std::memcmp(Font::glyph_bitmap('l'), Font::glyph_bitmap('I'), Font::glyph_height), 0);
}

} // namespace

TEST(BundledFonts, EveryRegisteredFontIsAUsableBitmapFont) {
  using namespace structo::examples::fonts;
  expect_sane_bitmap_font<terminus_8x16>();
  expect_sane_bitmap_font<terminus_bold_8x16>();
  expect_sane_bitmap_font<terminus_8x14>();
  expect_sane_bitmap_font<spleen_8x16>();
  expect_sane_bitmap_font<dejavu_sans_mono_8x16>();
  static_assert(terminus_8x14::glyph_height == 14 && spleen_8x16::glyph_height == 16);
}

TEST(BundledFonts, SelectFontDispatchesByNameAndRejectsUnknown) {
  using namespace structo::examples::fonts;
  auto height_of = [](auto tag) { return static_cast<int>(decltype(tag)::type::glyph_height); };
  int out = 0;
  EXPECT_TRUE(visit_font("terminus-14", height_of, out));
  EXPECT_EQ(out, 14);
  EXPECT_TRUE(visit_font("spleen", height_of, out));
  EXPECT_EQ(out, 16);
  EXPECT_FALSE(visit_font("comic-sans", height_of, out));
  for (const font_entry &e : font_list)
    EXPECT_TRUE(visit_font(e.name, height_of, out)) << e.name;
}
