#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
#
# SPDX-License-Identifier: BSD-2-Clause
"""Generates C++ system-register accessor headers from the per-architecture
YAML files under `scripts/sysregs/` (hand-maintained; see each file's header
comment).

Each YAML register becomes a small value-type struct holding a single `raw`
member plus, when the compiler is targeting a matching architecture,
`read()`/`write()` accessors implemented with inline asm (`mrs`/`msr`,
`mrc`/`mcr`, `csrr`/`csrw`, `mov %crN`, `pushf`/`popf`, `rdmsr`/`wrmsr`).

Every register currently has an empty ``fields: []`` list in the YAML, so no
named bit-field accessors are generated yet; the struct layout and codegen
below are written so that named `pte_bit_field` aliases can be added for a
register's `fields` later without changing its public shape (`raw` stays the
first member, `read()`/`write()` keep their current signatures).

Generated types live in a dedicated `sysreg_raw` nested namespace (e.g.
`structo::arch::arm64::sysreg_raw`) specifically to avoid colliding with the
hand-curated, bit-field-documented register types in files such as
`structo/arch/arm64/mmu_regs.hpp` (e.g. `structo::arch::arm64::sctlr_el1`),
which may share the same register name.
"""
from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - environment guard
    sys.exit("PyYAML is required to run this script (pip install pyyaml)")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
INCLUDE_ROOT = REPO_ROOT / "include" / "structo" / "arch"

HEADER_PREAMBLE = """\
// SPDX-FileCopyrightText: {year} Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

// Generated by scripts/sysregs/gen_sysreg_headers.py from
// scripts/sysregs/{yaml_name} -- do not edit by hand.
//
// Each struct below is a thin wrapper around one raw system register value
// plus, when compiling for a matching target architecture, `read()`/
// `write()` accessors implemented with inline asm. A register whose YAML
// `fields` list is non-empty also gets a nested `bits` type (one
// `structo::arch::pte_bit_field<LowBit, NumBits>` alias per field) and, per
// field, a `<name>()` getter plus a `set_<name>()` fluent setter -- `test()`/
// `set_bit()` for a 1-bit field, `get()`/`set()` otherwise. A register with
// an empty `fields` list only exposes `raw`.

#pragma once

#include <cstdint>
{pte_field_include}
"""

PTE_FIELD_INCLUDE = "#include <structo/arch/pte_field.hpp>\n"


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def parse_fields(fields: list[str]) -> list[tuple[str, int, int]]:
    """Parses each compact ``"name:bit:len"`` YAML field string into
    ``(name, bit, len)``."""
    parsed = []
    for spec in fields:
        field_name, bit, length = spec.split(":")
        parsed.append((field_name, int(bit), int(length)))
    return parsed


def emit_bitfield_members(fields: list[str], int_type: str) -> str:
    """Emits a nested `bits` type plus per-field getter/fluent-setter
    methods for a register's `fields` list, or `""` if it is empty."""
    if not fields:
        return ""
    parsed = parse_fields(fields)

    lines = ["  struct bits {"]
    for field_name, bit, length in parsed:
        lines.append(f"    using {field_name} = ::structo::arch::pte_bit_field<{bit}, {length}, {int_type}>;")
    lines.append("  };")
    lines.append("")
    for field_name, bit, length in parsed:
        if length == 1:
            lines.append(f"  [[nodiscard]] constexpr bool {field_name}() const noexcept {{ return bits::{field_name}::test(raw); }}")
            lines.append(
                f"  constexpr auto &set_{field_name}(bool value) noexcept {{ raw = bits::{field_name}::set_bit(raw, value); return *this; }}"
            )
        else:
            lines.append(
                f"  [[nodiscard]] constexpr {int_type} {field_name}() const noexcept {{ return bits::{field_name}::get(raw); }}"
            )
            lines.append(
                f"  constexpr auto &set_{field_name}({int_type} value) noexcept "
                f"{{ raw = bits::{field_name}::set(raw, value); return *this; }}"
            )
    lines.append("")
    return "\n".join(lines) + "\n"


def _doc_suffix(fields: list[str]) -> str:
    return "no named fields yet" if not fields else f"{len(fields)} named field(s)"


def cpp_struct_mrs_msr(name: str, enc: dict, fields: list[str]) -> str:
    sysreg = f"S{enc['op0']}_{enc['op1']}_C{enc['crn']}_C{enc['crm']}_{enc['op2']}"
    bitfields = emit_bitfield_members(fields, "std::uint64_t")
    return f"""\
/** @brief Raw accessor for the `{name.upper()}` AArch64 system register ({_doc_suffix(fields)}). */
struct {name} {{
  std::uint64_t raw{{0}};

{bitfields}#if defined(__aarch64__)
  [[nodiscard]] static {name} read() noexcept {{
    std::uint64_t value;
    asm volatile("mrs %0, {sysreg}" : "=r"(value));
    return {name}{{value}};
  }}
  void write() const noexcept {{ asm volatile("msr {sysreg}, %0" ::"r"(raw) : "memory"); }}
#endif // defined(__aarch64__)
}};
"""


def cpp_struct_coproc(name: str, enc: dict, fields: list[str]) -> str:
    coproc = enc["coproc"]
    opc1, crn, crm, opc2 = enc["opc1"], enc["crn"], enc["crm"], enc["opc2"]
    bitfields = emit_bitfield_members(fields, "std::uint32_t")
    return f"""\
/** @brief Raw accessor for the AArch32 `{name.upper()}` coprocessor register ({_doc_suffix(fields)}). */
struct {name} {{
  std::uint32_t raw{{0}};

{bitfields}#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static {name} read() noexcept {{
    std::uint32_t value;
    asm volatile("mrc {coproc}, {opc1}, %0, c{crn}, c{crm}, {opc2}" : "=r"(value));
    return {name}{{value}};
  }}
  void write() const noexcept {{ asm volatile("mcr {coproc}, {opc1}, %0, c{crn}, c{crm}, {opc2}" ::"r"(raw)); }}
#endif // defined(__arm__) && !defined(__aarch64__)
}};
"""


def cpp_struct_coproc64(name: str, enc: dict, fields: list[str]) -> str:
    """AArch32 LPAE-style 64-bit coprocessor register, transferred as a
    register pair via `mrrc`/`mcrr` (e.g. `TTBR0`/`TTBR1`/`PAR` in their
    LPAE long-descriptor form, `VTTBR`, `HTTBR`, and the 64-bit generic
    timer registers). `%Q0`/`%R0` let GCC/Clang pick the low/high half of
    the 64-bit operand's register pair."""
    coproc = enc["coproc"]
    opc1, crm = enc["opc1"], enc["crm"]
    bitfields = emit_bitfield_members(fields, "std::uint64_t")
    return f"""\
/** @brief Raw accessor for the AArch32 64-bit `{name.upper()}` coprocessor register pair ({_doc_suffix(fields)}). */
struct {name} {{
  std::uint64_t raw{{0}};

{bitfields}#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static {name} read() noexcept {{
    std::uint64_t value;
    asm volatile("mrrc {coproc}, {opc1}, %Q0, %R0, c{crm}" : "=r"(value));
    return {name}{{value}};
  }}
  void write() const noexcept {{ asm volatile("mcrr {coproc}, {opc1}, %Q0, %R0, c{crm}" ::"r"(raw)); }}
#endif // defined(__arm__) && !defined(__aarch64__)
}};
"""


def cpp_struct_banked(name: str, enc: dict, fields: list[str]) -> str:
    """AArch32 Virtualization-Extensions banked-register transfer: the
    architected way to read/write another exception mode's banked `SPSR`
    without switching into that mode (`CPS`) -- switching mode to reach,
    say, `SPSR_irq` is unsafe from Hyp mode (its banked-mode-switch rules
    differ from the other modes), and the AArch64 EL2 mnemonic form
    (`mrs x0, spsr_irq`) does not exist on ARMv7 and traps as an
    undefined instruction. Requires the Virtualization Extensions
    (ARMv7VE+); `.arch_extension virt` is emitted locally so the
    enclosing translation unit can still target a plain `armv7-a`
    baseline and only this asm block needs the extension."""
    reg = enc["reg"]
    bitfields = emit_bitfield_members(fields, "std::uint32_t")
    return f"""\
/** @brief Raw accessor for the AArch32 Virtualization-Extensions banked `{reg}` register ({_doc_suffix(fields)}). */
struct {name} {{
  std::uint32_t raw{{0}};

{bitfields}#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static {name} read() noexcept {{
    std::uint32_t value;
    asm volatile(".arch_extension virt\\n\\t"
                 "mrs %0, {reg}" : "=r"(value));
    return {name}{{value}};
  }}
  void write() const noexcept {{
    asm volatile(".arch_extension virt\\n\\t"
                 "msr {reg}, %0" ::"r"(raw));
  }}
#endif // defined(__arm__) && !defined(__aarch64__)
}};
"""


def cpp_struct_status(name: str, enc: dict, fields: list[str]) -> str:
    """AArch32 CPSR/SPSR: plain `mrs`/`msr` (no coprocessor tuple)."""
    reg = enc["reg"]
    bitfields = emit_bitfield_members(fields, "std::uint32_t")
    return f"""\
/** @brief Raw accessor for the AArch32 `{reg.upper()}` status register ({_doc_suffix(fields)}). */
struct {name} {{
  std::uint32_t raw{{0}};

{bitfields}#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static {name} read() noexcept {{
    std::uint32_t value;
    asm volatile("mrs %0, {reg}" : "=r"(value));
    return {name}{{value}};
  }}
  void write() const noexcept {{ asm volatile("msr {reg}_fsxc, %0" ::"r"(raw)); }}
#endif // defined(__arm__) && !defined(__aarch64__)
}};
"""


def cpp_struct_csr(name: str, enc: dict, fields: list[str]) -> str:
    addr = enc["address"]
    bitfields = emit_bitfield_members(fields, "unsigned long")
    return f"""\
/** @brief Raw accessor for the RISC-V `{name}` CSR (address {hex(addr)}; {_doc_suffix(fields)}). */
struct {name} {{
  unsigned long raw{{0}};

{bitfields}#if defined(__riscv)
  [[nodiscard]] static {name} read() noexcept {{
    unsigned long value;
    asm volatile("csrr %0, {hex(addr)}" : "=r"(value));
    return {name}{{value}};
  }}
  void write() const noexcept {{ asm volatile("csrw {hex(addr)}, %0" ::"r"(raw)); }}
#endif // defined(__riscv)
}};
"""


def _x86_cr_body(name: str, reg: str, int_type: str, guard: str) -> str:
    return f"""\
#if defined({guard})
  [[nodiscard]] static {name} read() noexcept {{
    {int_type} value;
    asm volatile("mov %%{reg}, %0" : "=r"(value));
    return {name}{{value}};
  }}
  void write() const noexcept {{ asm volatile("mov %0, %%{reg}" ::"r"(raw) : "memory"); }}
#endif // defined({guard})
"""


def cpp_struct_x86(name: str, entries_by_width: dict[int, dict]) -> str:
    """Emits one struct covering both the 32-bit and 64-bit variants of a
    register (guarded internally by `__i386__`/`__x86_64__`), matching the
    existing unified `structo/arch/x86/*.hpp` convention."""
    widths = sorted(entries_by_width.keys())
    any_kind = entries_by_width[widths[0]]["encoding"]["kind"]
    # MSR access is architecturally mode-independent (always a 64-bit value
    # regardless of whether the code executes in 32-bit or 64-bit mode), so
    # it is emitted once under a single combined guard instead of per-width.
    mode_independent = any_kind == "rdmsr_wrmsr"

    all_fields = [f for width in widths for f in entries_by_width[width].get("fields", [])]
    lines = [
        f"/** @brief Raw accessor for the x86 `{name.upper()}` register ({_doc_suffix(all_fields)}). */",
        f"struct {name} {{",
    ]

    if mode_independent or widths == [64]:
        lines.append("  std::uint64_t raw{0};")
    elif widths == [32]:
        lines.append("  std::uint32_t raw{0};")
    else:
        lines.append("#if defined(__x86_64__)")
        lines.append("  std::uint64_t raw{0};")
        lines.append("#else")
        lines.append("  std::uint32_t raw{0};")
        lines.append("#endif")
    lines.append("")

    if mode_independent or widths in ([64], [32]):
        int_type = "std::uint64_t" if (mode_independent or widths == [64]) else "std::uint32_t"
        bitfields = emit_bitfield_members(entries_by_width[widths[0]].get("fields", []), int_type)
        if bitfields:
            lines.append(bitfields.rstrip("\n"))
            lines.append("")
    elif all_fields:
        # Raw's type differs by mode here (no single guard covers both), so
        # the `bits` alias and accessors must be duplicated per-width using
        # that width's own integer type.
        lines.append("#if defined(__x86_64__)")
        bitfields64 = emit_bitfield_members(entries_by_width[64].get("fields", []), "std::uint64_t")
        if bitfields64:
            lines.append(bitfields64.rstrip("\n"))
        lines.append("#else")
        bitfields32 = emit_bitfield_members(entries_by_width[32].get("fields", []), "std::uint32_t")
        if bitfields32:
            lines.append(bitfields32.rstrip("\n"))
        lines.append("#endif")
        lines.append("")

    if mode_independent:
        msr = entries_by_width[widths[0]]["encoding"]["msr"]
        if widths == [32]:
            guard = "defined(__i386__)"
        elif widths == [64]:
            guard = "defined(__x86_64__)"
        else:
            guard = "defined(__i386__) || defined(__x86_64__)"
        body = f"""\
#if {guard}
  [[nodiscard]] static {name} read() noexcept {{
    std::uint32_t lo, hi;
    asm volatile("rdmsr" : "=a"(lo), "=d"(hi) : "c"({hex(msr)}));
    return {name}{{(static_cast<std::uint64_t>(hi) << 32) | lo}};
  }}
  void write() const noexcept {{
    const std::uint32_t lo = static_cast<std::uint32_t>(raw);
    const std::uint32_t hi = static_cast<std::uint32_t>(raw >> 32);
    asm volatile("wrmsr" ::"c"({hex(msr)}), "a"(lo), "d"(hi));
  }}
#endif // {guard}
"""
        lines.append(body.rstrip("\n"))
    else:
        for width in widths:
            enc = entries_by_width[width]["encoding"]
            guard = "__x86_64__" if width == 64 else "__i386__"
            kind = enc["kind"]
            if kind == "mov_cr":
                int_type = "std::uint64_t" if width == 64 else "std::uint32_t"
                lines.append(_x86_cr_body(name, enc["reg"], int_type, guard).rstrip("\n"))
            elif kind == "pushf_popf":
                int_type = "std::uint64_t" if width == 64 else "std::uint32_t"
                suffix = "q" if width == 64 else "d"
                body = f"""\
#if defined({guard})
  [[nodiscard]] static {name} read() noexcept {{
    {int_type} value;
    asm volatile("pushf{suffix}\\n\\tpop %0" : "=r"(value) :: "memory");
    return {name}{{value}};
  }}
  void write() const noexcept {{
    asm volatile("push %0\\n\\tpopf{suffix}" ::"r"(raw) : "cc", "memory");
  }}
#endif // defined({guard})
"""
                lines.append(body.rstrip("\n"))
            else:
                raise ValueError(f"unsupported x86 encoding kind: {kind}")

    lines.append("};")
    return "\n".join(lines) + "\n"


ARM_STRUCT_FNS = {
    "coproc": cpp_struct_coproc,
    "coproc64": cpp_struct_coproc64,
    "status": cpp_struct_status,
    "banked": cpp_struct_banked,
}


def cpp_struct_arm(name: str, enc: dict, fields: list[str]) -> str:
    fn = ARM_STRUCT_FNS.get(enc["kind"])
    if fn is None:
        raise ValueError(f"unsupported arm encoding kind: {enc['kind']}")
    return fn(name, enc, fields)


def _any_fields(*docs: dict) -> bool:
    return any(reg.get("fields") for doc in docs for reg in doc.get("registers", []))


def generate_simple_arch(yaml_path: Path, struct_fn, namespace_arch: str) -> str:
    doc = load_yaml(yaml_path)
    parts = [
        HEADER_PREAMBLE.format(
            year=datetime.date.today().year,
            yaml_name=yaml_path.name,
            pte_field_include=PTE_FIELD_INCLUDE if _any_fields(doc) else "",
        )
    ]
    parts.append(f"namespace structo::arch::{namespace_arch}::sysreg_raw {{\n\n")
    for reg in doc["registers"]:
        parts.append(struct_fn(reg["name"], reg["encoding"], reg.get("fields", [])))
        parts.append("\n")
    parts.append(f"}} // namespace structo::arch::{namespace_arch}::sysreg_raw\n")
    return "".join(parts)


def generate_x86(yaml_32: Path, yaml_64: Path) -> str:
    doc32 = load_yaml(yaml_32) if yaml_32.exists() else {"registers": []}
    doc64 = load_yaml(yaml_64) if yaml_64.exists() else {"registers": []}

    # Key by which YAML file a register came from (its origin architecture
    # width), not its declared register width: mode-independent registers
    # (MSRs) always declare width 64 but may only appear in one file (e.g.
    # FS_BASE/GS_BASE are 64-bit-only), and that presence must drive which
    # `__i386__`/`__x86_64__` guard is emitted.
    merged: dict[str, dict[int, dict]] = {}
    for reg in doc32["registers"]:
        merged.setdefault(reg["name"], {})[32] = reg
    for reg in doc64["registers"]:
        merged.setdefault(reg["name"], {})[64] = reg

    parts = [
        HEADER_PREAMBLE.format(
            year=datetime.date.today().year,
            yaml_name=f"{yaml_32.name} and {yaml_64.name}",
            pte_field_include=PTE_FIELD_INCLUDE if _any_fields(doc32, doc64) else "",
        )
    ]
    parts.append("namespace structo::arch::x86::sysreg_raw {\n\n")
    for name in sorted(merged.keys()):
        parts.append(cpp_struct_x86(name, merged[name]))
        parts.append("\n")
    parts.append("} // namespace structo::arch::x86::sysreg_raw\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yaml-dir", type=Path, default=SCRIPT_DIR)
    parser.add_argument("--include-root", type=Path, default=INCLUDE_ROOT)
    args = parser.parse_args()

    jobs = [
        ("arm64", args.yaml_dir / "arm64.yaml", cpp_struct_mrs_msr, "arm64"),
        ("arm", args.yaml_dir / "arm.yaml", cpp_struct_arm, "arm"),
        ("riscv", args.yaml_dir / "riscv.yaml", cpp_struct_csr, "riscv"),
    ]

    for arch, yaml_path, struct_fn, namespace_arch in jobs:
        if not yaml_path.exists():
            print(f"warning: {yaml_path} not found, skipping {arch}", file=sys.stderr)
            continue
        text = generate_simple_arch(yaml_path, struct_fn, namespace_arch)
        out_path = args.include_root / arch / "sysregs_generated.hpp"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        print(f"{arch}: wrote {out_path}")

    yaml_x86 = args.yaml_dir / "x86.yaml"
    yaml_x86_64 = args.yaml_dir / "x86_64.yaml"
    if yaml_x86.exists() or yaml_x86_64.exists():
        text = generate_x86(yaml_x86, yaml_x86_64)
        out_path = args.include_root / "x86" / "sysregs_generated.hpp"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        print(f"x86: wrote {out_path}")
    else:
        print(f"warning: neither {yaml_x86} nor {yaml_x86_64} found, skipping x86", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
