#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
#
# SPDX-License-Identifier: BSD-2-Clause

"""Regenerates `include/structo/sync/gdb_printers.hpp` from `tools/gdb/structo_printers.py`.

The generated header embeds the exact contents of `structo_printers.py` into
the `.debug_gdb_scripts` ELF/COFF section as a GDB "Python text" entry (see
https://sourceware.org/gdb/onlinedocs/gdb/dotdebug_005fgdb_005fscripts-section.html),
so any binary that includes the header gets GDB pretty printers for structo
types auto-loaded with no extra configuration (beyond GDB's standard
`auto-load safe-path`).

Run this script whenever `tools/gdb/structo_printers.py` changes:

    python3 tools/gdb/generate_embedded_header.py

Do not hand-edit the generated header; it is a mechanical transcription of
the printer script with two layers of string escaping applied (once for the
GNU assembler's `.ascii` string syntax, once for the C++ string literal that
the assembly is written as).

This mirrors reloco's `tools/gdb/generate_embedded_header.py` byte-for-byte
in approach (see that project's `docs/gdb-pretty-printers.md`); only the
source/destination paths and embedded script name differ.
"""

import pathlib
import sys

SCRIPT_NAME = "structo-pretty-printers.py"
CHUNK_SIZE = 96  # Original source characters per generated .ascii line, for readability only.


def _cpp_escape(text):
    """Escapes text (already GAS-escaped) for a C++ string literal."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _gas_escape_char(ch):
    """Escapes a single source character for a GNU-assembler `.ascii` string."""
    if ch == "\\":
        return "\\\\"
    if ch == '"':
        return '\\"'
    if ch == "\n":
        return "\\n"
    return ch


def _emit_ascii_lines(raw_text):
    """Yields C++ source lines, each holding one `.ascii "...\\n"` directive.

    Escaping is computed and chunked one *original* character at a time (an
    original character always maps to a complete, self-contained escape
    token) so a chunk boundary can never split a multi-character escape
    sequence across two `.ascii` string literals.
    """
    tokens = [_cpp_escape(_gas_escape_char(ch)) for ch in raw_text]
    for i in range(0, len(tokens), CHUNK_SIZE):
        piece = "".join(tokens[i : i + CHUNK_SIZE])
        yield '    ".ascii \\"' + piece + '\\"\\n"\n'


def generate(printers_source):
    lines = []
    lines.append("// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>\n")
    lines.append("//\n")
    lines.append("// SPDX-License-Identifier: BSD-2-Clause\n")
    lines.append("\n")
    lines.append("#pragma once\n")
    lines.append("\n")
    lines.append("// std-interop-file: embeds structo_printers.py as asm string-literal data, not C++ code\n")
    lines.append("\n")
    lines.append("/** @file gdb_printers.hpp\n")
    lines.append(" * @brief Embeds GDB pretty printers for structo::sync types into the binary.\n")
    lines.append(" *\n")
    lines.append(" * Including this header anywhere in a program (typically once, from the\n")
    lines.append(" * translation unit containing `main`) embeds the full contents of\n")
    lines.append(" * `tools/gdb/structo_printers.py` into a `.debug_gdb_scripts` section via\n")
    lines.append(" * inline assembly. When the resulting binary is loaded in GDB, GDB\n")
    lines.append(" * auto-loads and runs that script, registering pretty printers for every\n")
    lines.append(" * `structo::sync` primitive -- no `source` command, no `<binary>-gdb.py`\n")
    lines.append(" * file, and no `sys.path` setup required.\n")
    lines.append(" *\n")
    lines.append(" * This still requires GDB's `auto-load safe-path` to include the path of\n")
    lines.append(" * the binary containing this section (GDB disables auto-loading from\n")
    lines.append(" * untrusted locations by default); see\n")
    lines.append(" * https://sourceware.org/gdb/onlinedocs/gdb/Auto_002dloading-safe-path.html\n")
    lines.append(" *\n")
    lines.append(" * This file is generated by `tools/gdb/generate_embedded_header.py` from\n")
    lines.append(" * `tools/gdb/structo_printers.py` -- do not hand-edit it. Regenerate it\n")
    lines.append(" * whenever the printer script changes.\n")
    lines.append(" *\n")
    lines.append(" * Embedding costs a copy of the (small) Python source in every\n")
    lines.append(" * translation unit that includes this header for a *distinct* binary;\n")
    lines.append(" * the `\"MS\"` section flags let the linker fold identical copies within\n")
    lines.append(" * the same binary into one, so including it from multiple translation\n")
    lines.append(" * units of the same program is free.\n")
    lines.append(" *\n")
    lines.append(" * The `.debug_gdb_scripts` mechanism relies on GNU-assembler inline `asm`\n")
    lines.append(" * syntax and is only meaningful to GDB, so this header is a silent no-op\n")
    lines.append(" * -- it defines nothing and emits no section -- on compilers other than\n")
    lines.append(" * Clang/GCC (e.g. MSVC). Guarded on `__clang__`/`__GNUC__` rather than\n")
    lines.append(" * platform, so it also no-ops under `clang-cl`, which defines `_MSC_VER`\n")
    lines.append(" * but not GNU inline-asm syntax in its default mode.\n")
    lines.append(" *\n")
    lines.append(" * This follows the exact same mechanism as reloco's own\n")
    lines.append(" * `reloco/gdb_printers.hpp`; see that header and\n")
    lines.append(" * `docs/gdb-pretty-printers.md` for the full rationale.\n")
    lines.append(" */\n")
    lines.append("\n")
    lines.append("#if defined(__clang__) || defined(__GNUC__)\n")
    lines.append("\n")
    lines.append("// clang-format off\n")
    lines.append("asm(\n")
    lines.append('    ".pushsection \\".debug_gdb_scripts\\", \\"MS\\",@progbits,1\\n"\n')
    lines.append('    ".byte 4\\n" /* SECTION_SCRIPT_ID_PYTHON_TEXT */\n')
    lines.extend(_emit_ascii_lines(SCRIPT_NAME + "\n" + printers_source))
    lines.append('    ".byte 0\\n"\n')
    lines.append('    ".popsection\\n"\n')
    lines.append(");\n")
    lines.append("// clang-format on\n")
    lines.append("\n")
    lines.append("#endif // defined(__clang__) || defined(__GNUC__)\n")
    return "".join(lines)


def main():
    repo_root = pathlib.Path(__file__).resolve().parent.parent.parent
    printers_path = repo_root / "tools" / "gdb" / "structo_printers.py"
    header_path = repo_root / "include" / "structo" / "sync" / "gdb_printers.hpp"

    printers_source = printers_path.read_text(encoding="utf-8")
    header_path.write_text(generate(printers_source), encoding="utf-8")
    print("wrote %s (%d bytes of embedded script)" % (header_path, len(printers_source)))


if __name__ == "__main__":
    sys.exit(main())
