// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

// Generated by scripts/sysregs/gen_sysreg_headers.py from
// scripts/sysregs/x86.yaml and x86_64.yaml -- do not edit by hand.
//
// Each struct below is a thin wrapper around one raw system register value
// plus, when compiling for a matching target architecture, `read()`/
// `write()` accessors implemented with inline asm. A register whose YAML
// `fields` list is non-empty also gets a nested `bits` type (one
// `structo::arch::pte_bit_field<LowBit, NumBits>` alias per field) and, per
// field, a `<name>()` getter plus a `set_<name>()` fluent setter -- `test()`/
// `set_bit()` for a 1-bit field, `get()`/`set()` otherwise. A register with
// an empty `fields` list only exposes `raw`.

#pragma once

#include <cstdint>

namespace structo::arch::x86::sysreg_raw {

/** @brief Raw accessor for the x86 `CR0` register (no named fields yet). */
struct cr0 {
#if defined(__x86_64__)
  std::uint64_t raw{0};
#else
  std::uint32_t raw{0};
#endif

#if defined(__i386__)
  [[nodiscard]] static cr0 read() noexcept {
    std::uint32_t value;
    asm volatile("mov %%cr0, %0" : "=r"(value));
    return cr0{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr0" ::"r"(raw) : "memory"); }
#endif // defined(__i386__)
#if defined(__x86_64__)
  [[nodiscard]] static cr0 read() noexcept {
    std::uint64_t value;
    asm volatile("mov %%cr0, %0" : "=r"(value));
    return cr0{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr0" ::"r"(raw) : "memory"); }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `CR2` register (no named fields yet). */
struct cr2 {
#if defined(__x86_64__)
  std::uint64_t raw{0};
#else
  std::uint32_t raw{0};
#endif

#if defined(__i386__)
  [[nodiscard]] static cr2 read() noexcept {
    std::uint32_t value;
    asm volatile("mov %%cr2, %0" : "=r"(value));
    return cr2{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr2" ::"r"(raw) : "memory"); }
#endif // defined(__i386__)
#if defined(__x86_64__)
  [[nodiscard]] static cr2 read() noexcept {
    std::uint64_t value;
    asm volatile("mov %%cr2, %0" : "=r"(value));
    return cr2{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr2" ::"r"(raw) : "memory"); }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `CR3` register (no named fields yet). */
struct cr3 {
#if defined(__x86_64__)
  std::uint64_t raw{0};
#else
  std::uint32_t raw{0};
#endif

#if defined(__i386__)
  [[nodiscard]] static cr3 read() noexcept {
    std::uint32_t value;
    asm volatile("mov %%cr3, %0" : "=r"(value));
    return cr3{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr3" ::"r"(raw) : "memory"); }
#endif // defined(__i386__)
#if defined(__x86_64__)
  [[nodiscard]] static cr3 read() noexcept {
    std::uint64_t value;
    asm volatile("mov %%cr3, %0" : "=r"(value));
    return cr3{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr3" ::"r"(raw) : "memory"); }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `CR4` register (no named fields yet). */
struct cr4 {
#if defined(__x86_64__)
  std::uint64_t raw{0};
#else
  std::uint32_t raw{0};
#endif

#if defined(__i386__)
  [[nodiscard]] static cr4 read() noexcept {
    std::uint32_t value;
    asm volatile("mov %%cr4, %0" : "=r"(value));
    return cr4{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr4" ::"r"(raw) : "memory"); }
#endif // defined(__i386__)
#if defined(__x86_64__)
  [[nodiscard]] static cr4 read() noexcept {
    std::uint64_t value;
    asm volatile("mov %%cr4, %0" : "=r"(value));
    return cr4{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr4" ::"r"(raw) : "memory"); }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `CR8` register (no named fields yet). */
struct cr8 {
  std::uint64_t raw{0};

#if defined(__x86_64__)
  [[nodiscard]] static cr8 read() noexcept {
    std::uint64_t value;
    asm volatile("mov %%cr8, %0" : "=r"(value));
    return cr8{value};
  }
  void write() const noexcept { asm volatile("mov %0, %%cr8" ::"r"(raw) : "memory"); }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `EFLAGS` register (no named fields yet). */
struct eflags {
  std::uint32_t raw{0};

#if defined(__i386__)
  [[nodiscard]] static eflags read() noexcept {
    std::uint32_t value;
    asm volatile("pushfd\n\tpop %0" : "=r"(value) :: "memory");
    return eflags{value};
  }
  void write() const noexcept {
    asm volatile("push %0\n\tpopfd" ::"r"(raw) : "cc", "memory");
  }
#endif // defined(__i386__)
};

/** @brief Raw accessor for the x86 `IA32_EFER` register (no named fields yet). */
struct ia32_efer {
  std::uint64_t raw{0};

#if defined(__i386__) || defined(__x86_64__)
  [[nodiscard]] static ia32_efer read() noexcept {
    std::uint32_t lo, hi;
    asm volatile("rdmsr" : "=a"(lo), "=d"(hi) : "c"(0xc0000080));
    return ia32_efer{(static_cast<std::uint64_t>(hi) << 32) | lo};
  }
  void write() const noexcept {
    const std::uint32_t lo = static_cast<std::uint32_t>(raw);
    const std::uint32_t hi = static_cast<std::uint32_t>(raw >> 32);
    asm volatile("wrmsr" ::"c"(0xc0000080), "a"(lo), "d"(hi));
  }
#endif // defined(__i386__) || defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `IA32_FS_BASE` register (no named fields yet). */
struct ia32_fs_base {
  std::uint64_t raw{0};

#if defined(__x86_64__)
  [[nodiscard]] static ia32_fs_base read() noexcept {
    std::uint32_t lo, hi;
    asm volatile("rdmsr" : "=a"(lo), "=d"(hi) : "c"(0xc0000100));
    return ia32_fs_base{(static_cast<std::uint64_t>(hi) << 32) | lo};
  }
  void write() const noexcept {
    const std::uint32_t lo = static_cast<std::uint32_t>(raw);
    const std::uint32_t hi = static_cast<std::uint32_t>(raw >> 32);
    asm volatile("wrmsr" ::"c"(0xc0000100), "a"(lo), "d"(hi));
  }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `IA32_GS_BASE` register (no named fields yet). */
struct ia32_gs_base {
  std::uint64_t raw{0};

#if defined(__x86_64__)
  [[nodiscard]] static ia32_gs_base read() noexcept {
    std::uint32_t lo, hi;
    asm volatile("rdmsr" : "=a"(lo), "=d"(hi) : "c"(0xc0000101));
    return ia32_gs_base{(static_cast<std::uint64_t>(hi) << 32) | lo};
  }
  void write() const noexcept {
    const std::uint32_t lo = static_cast<std::uint32_t>(raw);
    const std::uint32_t hi = static_cast<std::uint32_t>(raw >> 32);
    asm volatile("wrmsr" ::"c"(0xc0000101), "a"(lo), "d"(hi));
  }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `IA32_KERNEL_GS_BASE` register (no named fields yet). */
struct ia32_kernel_gs_base {
  std::uint64_t raw{0};

#if defined(__x86_64__)
  [[nodiscard]] static ia32_kernel_gs_base read() noexcept {
    std::uint32_t lo, hi;
    asm volatile("rdmsr" : "=a"(lo), "=d"(hi) : "c"(0xc0000102));
    return ia32_kernel_gs_base{(static_cast<std::uint64_t>(hi) << 32) | lo};
  }
  void write() const noexcept {
    const std::uint32_t lo = static_cast<std::uint32_t>(raw);
    const std::uint32_t hi = static_cast<std::uint32_t>(raw >> 32);
    asm volatile("wrmsr" ::"c"(0xc0000102), "a"(lo), "d"(hi));
  }
#endif // defined(__x86_64__)
};

/** @brief Raw accessor for the x86 `RFLAGS` register (no named fields yet). */
struct rflags {
  std::uint64_t raw{0};

#if defined(__x86_64__)
  [[nodiscard]] static rflags read() noexcept {
    std::uint64_t value;
    asm volatile("pushfq\n\tpop %0" : "=r"(value) :: "memory");
    return rflags{value};
  }
  void write() const noexcept {
    asm volatile("push %0\n\tpopfq" ::"r"(raw) : "cc", "memory");
  }
#endif // defined(__x86_64__)
};

} // namespace structo::arch::x86::sysreg_raw
