// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

// Generated by scripts/sysregs/gen_sysreg_headers.py from
// scripts/sysregs/arm64.yaml -- do not edit by hand.
//
// Each struct below is a thin, bit-field-free wrapper around one raw system
// register value plus, when compiling for a matching target architecture,
// `read()`/`write()` accessors implemented with inline asm. No named
// bit-field accessors are generated yet (`fields` is empty for every
// register in the source YAML); re-running the generator after that YAML
// gains field data will add them here without otherwise changing this file.

#pragma once

#include <cstdint>

namespace structo::arch::arm64::sysreg_raw {

/** @brief Raw accessor for the `AFSR0_EL1` AArch64 system register (no named fields yet). */
struct afsr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static afsr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C5_C1_0" : "=r"(value));
    return afsr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C5_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AFSR0_EL12` AArch64 system register (no named fields yet). */
struct afsr0_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static afsr0_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C5_C1_0" : "=r"(value));
    return afsr0_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C5_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AFSR1_EL1` AArch64 system register (no named fields yet). */
struct afsr1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static afsr1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C5_C1_1" : "=r"(value));
    return afsr1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C5_C1_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AFSR1_EL12` AArch64 system register (no named fields yet). */
struct afsr1_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static afsr1_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C5_C1_1" : "=r"(value));
    return afsr1_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C5_C1_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AMAIR_EL1` AArch64 system register (no named fields yet). */
struct amair_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static amair_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C10_C3_0" : "=r"(value));
    return amair_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C10_C3_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AMAIR_EL12` AArch64 system register (no named fields yet). */
struct amair_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static amair_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C10_C3_0" : "=r"(value));
    return amair_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C10_C3_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APDAKEY_HI_EL1` AArch64 system register (no named fields yet). */
struct apdakey_hi_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apdakey_hi_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C2_1" : "=r"(value));
    return apdakey_hi_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C2_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APDAKEY_LO_EL1` AArch64 system register (no named fields yet). */
struct apdakey_lo_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apdakey_lo_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C2_0" : "=r"(value));
    return apdakey_lo_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APDBKEY_HI_EL1` AArch64 system register (no named fields yet). */
struct apdbkey_hi_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apdbkey_hi_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C2_3" : "=r"(value));
    return apdbkey_hi_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C2_3, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APDBKEY_LO_EL1` AArch64 system register (no named fields yet). */
struct apdbkey_lo_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apdbkey_lo_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C2_2" : "=r"(value));
    return apdbkey_lo_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C2_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APGAKEY_HI_EL1` AArch64 system register (no named fields yet). */
struct apgakey_hi_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apgakey_hi_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C3_1" : "=r"(value));
    return apgakey_hi_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C3_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APGAKEY_LO_EL1` AArch64 system register (no named fields yet). */
struct apgakey_lo_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apgakey_lo_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C3_0" : "=r"(value));
    return apgakey_lo_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C3_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APIAKEY_HI_EL1` AArch64 system register (no named fields yet). */
struct apiakey_hi_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apiakey_hi_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C1_1" : "=r"(value));
    return apiakey_hi_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C1_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APIAKEY_LO_EL1` AArch64 system register (no named fields yet). */
struct apiakey_lo_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apiakey_lo_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C1_0" : "=r"(value));
    return apiakey_lo_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APIBKEY_HI_EL1` AArch64 system register (no named fields yet). */
struct apibkey_hi_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apibkey_hi_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C1_3" : "=r"(value));
    return apibkey_hi_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C1_3, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `APIBKEY_LO_EL1` AArch64 system register (no named fields yet). */
struct apibkey_lo_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static apibkey_lo_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C1_2" : "=r"(value));
    return apibkey_lo_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C1_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CCSIDR_EL1` AArch64 system register (no named fields yet). */
struct ccsidr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static ccsidr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_1_C0_C0_0" : "=r"(value));
    return ccsidr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_1_C0_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CLIDR_EL1` AArch64 system register (no named fields yet). */
struct clidr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static clidr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_1_C0_C0_1" : "=r"(value));
    return clidr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_1_C0_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTKCTL_EL1` AArch64 system register (no named fields yet). */
struct cntkctl_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntkctl_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C14_C1_0" : "=r"(value));
    return cntkctl_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C14_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTKCTL_EL12` AArch64 system register (no named fields yet). */
struct cntkctl_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntkctl_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C14_C1_0" : "=r"(value));
    return cntkctl_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C14_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTP_CTL_EL0` AArch64 system register (no named fields yet). */
struct cntp_ctl_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntp_ctl_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C2_1" : "=r"(value));
    return cntp_ctl_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C2_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTP_CTL_EL02` AArch64 system register (no named fields yet). */
struct cntp_ctl_el02 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntp_ctl_el02 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C14_C2_1" : "=r"(value));
    return cntp_ctl_el02{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C14_C2_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTP_CVAL_EL0` AArch64 system register (no named fields yet). */
struct cntp_cval_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntp_cval_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C2_2" : "=r"(value));
    return cntp_cval_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C2_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTP_CVAL_EL02` AArch64 system register (no named fields yet). */
struct cntp_cval_el02 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntp_cval_el02 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C14_C2_2" : "=r"(value));
    return cntp_cval_el02{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C14_C2_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTP_TVAL_EL0` AArch64 system register (no named fields yet). */
struct cntp_tval_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntp_tval_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C2_0" : "=r"(value));
    return cntp_tval_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTPCT_EL0` AArch64 system register (no named fields yet). */
struct cntpct_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntpct_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C0_1" : "=r"(value));
    return cntpct_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTPCTSS_EL0` AArch64 system register (no named fields yet). */
struct cntpctss_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntpctss_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C0_5" : "=r"(value));
    return cntpctss_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C0_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTV_CTL_EL0` AArch64 system register (no named fields yet). */
struct cntv_ctl_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntv_ctl_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C3_1" : "=r"(value));
    return cntv_ctl_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C3_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTV_CTL_EL02` AArch64 system register (no named fields yet). */
struct cntv_ctl_el02 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntv_ctl_el02 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C14_C3_1" : "=r"(value));
    return cntv_ctl_el02{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C14_C3_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTV_CVAL_EL0` AArch64 system register (no named fields yet). */
struct cntv_cval_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntv_cval_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C3_2" : "=r"(value));
    return cntv_cval_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C3_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTV_CVAL_EL02` AArch64 system register (no named fields yet). */
struct cntv_cval_el02 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntv_cval_el02 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C14_C3_2" : "=r"(value));
    return cntv_cval_el02{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C14_C3_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CNTVCTSS_EL0` AArch64 system register (no named fields yet). */
struct cntvctss_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cntvctss_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C0_6" : "=r"(value));
    return cntvctss_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C0_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CONTEXTIDR_EL1` AArch64 system register (no named fields yet). */
struct contextidr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static contextidr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C13_C0_1" : "=r"(value));
    return contextidr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C13_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CONTEXTIDR_EL12` AArch64 system register (no named fields yet). */
struct contextidr_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static contextidr_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C13_C0_1" : "=r"(value));
    return contextidr_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C13_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CPACR_EL1` AArch64 system register (no named fields yet). */
struct cpacr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cpacr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C1_C0_2" : "=r"(value));
    return cpacr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C1_C0_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CPACR_EL12` AArch64 system register (no named fields yet). */
struct cpacr_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cpacr_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C1_C0_2" : "=r"(value));
    return cpacr_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C1_C0_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CSSELR_EL1` AArch64 system register (no named fields yet). */
struct csselr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static csselr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_2_C0_C0_0" : "=r"(value));
    return csselr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_2_C0_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CTR_EL0` AArch64 system register (no named fields yet). */
struct ctr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static ctr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C0_C0_1" : "=r"(value));
    return ctr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C0_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `DBGAUTHSTATUS_EL1` AArch64 system register (no named fields yet). */
struct dbgauthstatus_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static dbgauthstatus_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C7_C14_6" : "=r"(value));
    return dbgauthstatus_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C7_C14_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `DBGCLAIMCLR_EL1` AArch64 system register (no named fields yet). */
struct dbgclaimclr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static dbgclaimclr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C7_C9_6" : "=r"(value));
    return dbgclaimclr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C7_C9_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `DBGCLAIMSET_EL1` AArch64 system register (no named fields yet). */
struct dbgclaimset_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static dbgclaimset_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C7_C8_6" : "=r"(value));
    return dbgclaimset_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C7_C8_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `DBGPRCR_EL1` AArch64 system register (no named fields yet). */
struct dbgprcr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static dbgprcr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C1_C4_4" : "=r"(value));
    return dbgprcr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C1_C4_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ELR_EL1` AArch64 system register (no named fields yet). */
struct elr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static elr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C4_C0_1" : "=r"(value));
    return elr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C4_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ELR_EL12` AArch64 system register (no named fields yet). */
struct elr_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static elr_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C4_C0_1" : "=r"(value));
    return elr_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C4_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ESR_EL1` AArch64 system register (no named fields yet). */
struct esr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static esr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C5_C2_0" : "=r"(value));
    return esr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C5_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ESR_EL12` AArch64 system register (no named fields yet). */
struct esr_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static esr_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C5_C2_0" : "=r"(value));
    return esr_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C5_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `FAR_EL1` AArch64 system register (no named fields yet). */
struct far_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static far_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C6_C0_0" : "=r"(value));
    return far_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C6_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `FAR_EL12` AArch64 system register (no named fields yet). */
struct far_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static far_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C6_C0_0" : "=r"(value));
    return far_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C6_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `GCR_EL1` AArch64 system register (no named fields yet). */
struct gcr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static gcr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C1_C0_6" : "=r"(value));
    return gcr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C1_C0_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `GMID_EL1` AArch64 system register (no named fields yet). */
struct gmid_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static gmid_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_1_C0_C0_4" : "=r"(value));
    return gmid_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_1_C0_C0_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ICC_SGI1_R_EL1` AArch64 system register (no named fields yet). */
struct icc_sgi1_r_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static icc_sgi1_r_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C12_C11_5" : "=r"(value));
    return icc_sgi1_r_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C12_C11_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_AFR0_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_afr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_afr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C5_4" : "=r"(value));
    return id_aa64_afr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C5_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_AFR1_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_afr1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_afr1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C5_5" : "=r"(value));
    return id_aa64_afr1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C5_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_DFR0_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_dfr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_dfr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C5_0" : "=r"(value));
    return id_aa64_dfr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C5_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_DFR1_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_dfr1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_dfr1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C5_1" : "=r"(value));
    return id_aa64_dfr1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C5_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_ISAR0_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_isar0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_isar0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C6_0" : "=r"(value));
    return id_aa64_isar0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C6_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_ISAR1_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_isar1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_isar1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C6_1" : "=r"(value));
    return id_aa64_isar1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C6_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_ISAR2_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_isar2_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_isar2_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C6_2" : "=r"(value));
    return id_aa64_isar2_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C6_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_MMFR0_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_mmfr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_mmfr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C7_0" : "=r"(value));
    return id_aa64_mmfr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C7_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_MMFR1_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_mmfr1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_mmfr1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C7_1" : "=r"(value));
    return id_aa64_mmfr1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C7_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_MMFR2_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_mmfr2_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_mmfr2_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C7_2" : "=r"(value));
    return id_aa64_mmfr2_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C7_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_MMFR3_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_mmfr3_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_mmfr3_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C7_3" : "=r"(value));
    return id_aa64_mmfr3_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C7_3, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_MMFR4_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_mmfr4_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_mmfr4_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C7_4" : "=r"(value));
    return id_aa64_mmfr4_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C7_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_PFR0_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_pfr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_pfr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C4_0" : "=r"(value));
    return id_aa64_pfr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C4_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_PFR1_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_pfr1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_pfr1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C4_1" : "=r"(value));
    return id_aa64_pfr1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C4_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_PFR2_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_pfr2_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_pfr2_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C4_2" : "=r"(value));
    return id_aa64_pfr2_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C4_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_AA64_ZFR0_EL1` AArch64 system register (no named fields yet). */
struct id_aa64_zfr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_aa64_zfr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C4_4" : "=r"(value));
    return id_aa64_zfr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C4_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ID_ISAR5_EL1` AArch64 system register (no named fields yet). */
struct id_isar5_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static id_isar5_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C2_5" : "=r"(value));
    return id_isar5_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C2_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MAIR_EL1` AArch64 system register (no named fields yet). */
struct mair_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mair_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C10_C2_0" : "=r"(value));
    return mair_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C10_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MAIR_EL12` AArch64 system register (no named fields yet). */
struct mair_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mair_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C10_C2_0" : "=r"(value));
    return mair_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C10_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MDCCINT_EL1` AArch64 system register (no named fields yet). */
struct mdccint_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mdccint_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C0_C2_0" : "=r"(value));
    return mdccint_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C0_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MDCCSR_EL0` AArch64 system register (no named fields yet). */
struct mdccsr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mdccsr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_3_C0_C1_0" : "=r"(value));
    return mdccsr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S2_3_C0_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MDSCR_EL1` AArch64 system register (no named fields yet). */
struct mdscr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mdscr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C0_C2_2" : "=r"(value));
    return mdscr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C0_C2_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MIDR_EL1` AArch64 system register (no named fields yet). */
struct midr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static midr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C0_0" : "=r"(value));
    return midr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MPIDR_EL1` AArch64 system register (no named fields yet). */
struct mpidr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mpidr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C0_5" : "=r"(value));
    return mpidr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C0_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MVFR0_EL1` AArch64 system register (no named fields yet). */
struct mvfr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mvfr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C3_0" : "=r"(value));
    return mvfr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C3_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MVFR1_EL1` AArch64 system register (no named fields yet). */
struct mvfr1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mvfr1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C3_1" : "=r"(value));
    return mvfr1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C3_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `OSDLR_EL1` AArch64 system register (no named fields yet). */
struct osdlr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static osdlr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C1_C3_4" : "=r"(value));
    return osdlr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C1_C3_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `OSLAR_EL1` AArch64 system register (no named fields yet). */
struct oslar_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static oslar_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C1_C0_4" : "=r"(value));
    return oslar_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C1_C0_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `OSLSR_EL1` AArch64 system register (no named fields yet). */
struct oslsr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static oslsr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S2_0_C1_C1_4" : "=r"(value));
    return oslsr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S2_0_C1_C1_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMBIDR_EL1` AArch64 system register (no named fields yet). */
struct pmbidr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmbidr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C10_7" : "=r"(value));
    return pmbidr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C10_7, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMBLIMITR_EL1` AArch64 system register (no named fields yet). */
struct pmblimitr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmblimitr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C10_0" : "=r"(value));
    return pmblimitr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C10_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMBPTR_EL1` AArch64 system register (no named fields yet). */
struct pmbptr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmbptr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C10_1" : "=r"(value));
    return pmbptr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C10_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMBSR_EL1` AArch64 system register (no named fields yet). */
struct pmbsr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmbsr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C10_3" : "=r"(value));
    return pmbsr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C10_3, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMCCFILTR_EL0` AArch64 system register (no named fields yet). */
struct pmccfiltr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmccfiltr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C14_C15_7" : "=r"(value));
    return pmccfiltr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C14_C15_7, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMCCNTR_EL0` AArch64 system register (no named fields yet). */
struct pmccntr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmccntr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C13_0" : "=r"(value));
    return pmccntr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C13_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMCEID0_EL0` AArch64 system register (no named fields yet). */
struct pmceid0_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmceid0_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_6" : "=r"(value));
    return pmceid0_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMCEID1_EL0` AArch64 system register (no named fields yet). */
struct pmceid1_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmceid1_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_7" : "=r"(value));
    return pmceid1_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_7, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMCNTENCLR_EL0` AArch64 system register (no named fields yet). */
struct pmcntenclr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmcntenclr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_2" : "=r"(value));
    return pmcntenclr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMCNTENSET_EL0` AArch64 system register (no named fields yet). */
struct pmcntenset_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmcntenset_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_1" : "=r"(value));
    return pmcntenset_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMCR_EL0` AArch64 system register (no named fields yet). */
struct pmcr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmcr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_0" : "=r"(value));
    return pmcr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMINTENCLR_EL1` AArch64 system register (no named fields yet). */
struct pmintenclr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmintenclr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C14_2" : "=r"(value));
    return pmintenclr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C14_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMINTENSET_EL1` AArch64 system register (no named fields yet). */
struct pmintenset_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmintenset_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C14_1" : "=r"(value));
    return pmintenset_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C14_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMMIR_EL1` AArch64 system register (no named fields yet). */
struct pmmir_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmmir_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C14_6" : "=r"(value));
    return pmmir_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C14_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMOVSCLR_EL0` AArch64 system register (no named fields yet). */
struct pmovsclr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmovsclr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_3" : "=r"(value));
    return pmovsclr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_3, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMOVSSET_EL0` AArch64 system register (no named fields yet). */
struct pmovsset_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmovsset_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C14_3" : "=r"(value));
    return pmovsset_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C14_3, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSCR_EL1` AArch64 system register (no named fields yet). */
struct pmscr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmscr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_0" : "=r"(value));
    return pmscr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSELR_EL0` AArch64 system register (no named fields yet). */
struct pmselr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmselr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_5" : "=r"(value));
    return pmselr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSEVFR_EL1` AArch64 system register (no named fields yet). */
struct pmsevfr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmsevfr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_5" : "=r"(value));
    return pmsevfr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSFCR_EL1` AArch64 system register (no named fields yet). */
struct pmsfcr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmsfcr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_4" : "=r"(value));
    return pmsfcr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSICR_EL1` AArch64 system register (no named fields yet). */
struct pmsicr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmsicr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_2" : "=r"(value));
    return pmsicr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSIDR_EL1` AArch64 system register (no named fields yet). */
struct pmsidr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmsidr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_7" : "=r"(value));
    return pmsidr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_7, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSIRR_EL1` AArch64 system register (no named fields yet). */
struct pmsirr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmsirr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_3" : "=r"(value));
    return pmsirr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_3, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSLATFR_EL1` AArch64 system register (no named fields yet). */
struct pmslatfr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmslatfr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_6" : "=r"(value));
    return pmslatfr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSNEVFR_EL1` AArch64 system register (no named fields yet). */
struct pmsnevfr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmsnevfr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C9_C9_1" : "=r"(value));
    return pmsnevfr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C9_C9_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMSWINC_EL0` AArch64 system register (no named fields yet). */
struct pmswinc_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmswinc_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C12_4" : "=r"(value));
    return pmswinc_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C12_4, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMUSERENR_EL0` AArch64 system register (no named fields yet). */
struct pmuserenr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmuserenr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C14_0" : "=r"(value));
    return pmuserenr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C14_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMXEVCNTR_EL0` AArch64 system register (no named fields yet). */
struct pmxevcntr_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmxevcntr_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C13_2" : "=r"(value));
    return pmxevcntr_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C13_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `PMXEVTYPER_EL0` AArch64 system register (no named fields yet). */
struct pmxevtyper_el0 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static pmxevtyper_el0 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C9_C13_1" : "=r"(value));
    return pmxevtyper_el0{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C9_C13_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `RGSR_EL1` AArch64 system register (no named fields yet). */
struct rgsr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static rgsr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C1_C0_5" : "=r"(value));
    return rgsr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C1_C0_5, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `RNDRRS` AArch64 system register (no named fields yet). */
struct rndrrs {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static rndrrs read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C2_C4_1" : "=r"(value));
    return rndrrs{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C2_C4_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SCTLR_EL1` AArch64 system register (no named fields yet). */
struct sctlr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static sctlr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C1_C0_0" : "=r"(value));
    return sctlr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C1_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SCTLR_EL12` AArch64 system register (no named fields yet). */
struct sctlr_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static sctlr_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C1_C0_0" : "=r"(value));
    return sctlr_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C1_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SPSR_EL1` AArch64 system register (no named fields yet). */
struct spsr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static spsr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C4_C0_0" : "=r"(value));
    return spsr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C4_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SPSR_EL12` AArch64 system register (no named fields yet). */
struct spsr_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static spsr_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C4_C0_0" : "=r"(value));
    return spsr_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C4_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `REVIDR_EL1` AArch64 system register (no named fields yet). */
struct revidr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static revidr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C0_C0_6" : "=r"(value));
    return revidr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C0_C0_6, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TCO` AArch64 system register (no named fields yet). */
struct tco {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static tco read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_3_C4_C2_7" : "=r"(value));
    return tco{value};
  }
  void write() const noexcept { asm volatile("msr S3_3_C4_C2_7, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TCR_EL1` AArch64 system register (no named fields yet). */
struct tcr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static tcr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C0_2" : "=r"(value));
    return tcr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C0_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TCR_EL12` AArch64 system register (no named fields yet). */
struct tcr_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static tcr_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C2_C0_2" : "=r"(value));
    return tcr_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C2_C0_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TFSRE0_EL1` AArch64 system register (no named fields yet). */
struct tfsre0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static tfsre0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C5_C6_1" : "=r"(value));
    return tfsre0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C5_C6_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TFSR_EL1` AArch64 system register (no named fields yet). */
struct tfsr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static tfsr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C5_C6_0" : "=r"(value));
    return tfsr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C5_C6_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TTBR0_EL1` AArch64 system register (no named fields yet). */
struct ttbr0_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static ttbr0_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C0_0" : "=r"(value));
    return ttbr0_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TTBR0_EL12` AArch64 system register (no named fields yet). */
struct ttbr0_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static ttbr0_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C2_C0_0" : "=r"(value));
    return ttbr0_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C2_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TTBR1_EL1` AArch64 system register (no named fields yet). */
struct ttbr1_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static ttbr1_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C2_C0_1" : "=r"(value));
    return ttbr1_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C2_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TTBR1_EL12` AArch64 system register (no named fields yet). */
struct ttbr1_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static ttbr1_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C2_C0_1" : "=r"(value));
    return ttbr1_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C2_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `VBAR_EL1` AArch64 system register (no named fields yet). */
struct vbar_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static vbar_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C12_C0_0" : "=r"(value));
    return vbar_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C12_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `VBAR_EL12` AArch64 system register (no named fields yet). */
struct vbar_el12 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static vbar_el12 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_5_C12_C0_0" : "=r"(value));
    return vbar_el12{value};
  }
  void write() const noexcept { asm volatile("msr S3_5_C12_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ZCR_EL1` AArch64 system register (no named fields yet). */
struct zcr_el1 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static zcr_el1 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_0_C1_C2_0" : "=r"(value));
    return zcr_el1{value};
  }
  void write() const noexcept { asm volatile("msr S3_0_C1_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SCTLR_EL3` AArch64 system register (no named fields yet). */
struct sctlr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static sctlr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C1_C0_0" : "=r"(value));
    return sctlr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C1_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ACTLR_EL3` AArch64 system register (no named fields yet). */
struct actlr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static actlr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C1_C0_1" : "=r"(value));
    return actlr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C1_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SCR_EL3` AArch64 system register (no named fields yet). */
struct scr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static scr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C1_C1_0" : "=r"(value));
    return scr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C1_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SDER32_EL3` AArch64 system register (no named fields yet). */
struct sder32_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static sder32_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C1_C1_1" : "=r"(value));
    return sder32_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C1_C1_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `CPTR_EL3` AArch64 system register (no named fields yet). */
struct cptr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static cptr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C1_C1_2" : "=r"(value));
    return cptr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C1_C1_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MDCR_EL3` AArch64 system register (no named fields yet). */
struct mdcr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mdcr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C1_C3_1" : "=r"(value));
    return mdcr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C1_C3_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TTBR0_EL3` AArch64 system register (no named fields yet). */
struct ttbr0_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static ttbr0_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C2_C0_0" : "=r"(value));
    return ttbr0_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C2_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `TCR_EL3` AArch64 system register (no named fields yet). */
struct tcr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static tcr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C2_C0_2" : "=r"(value));
    return tcr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C2_C0_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SPSR_EL3` AArch64 system register (no named fields yet). */
struct spsr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static spsr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C4_C0_0" : "=r"(value));
    return spsr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C4_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ELR_EL3` AArch64 system register (no named fields yet). */
struct elr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static elr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C4_C0_1" : "=r"(value));
    return elr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C4_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `SP_EL2` AArch64 system register (no named fields yet). */
struct sp_el2 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static sp_el2 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C4_C1_0" : "=r"(value));
    return sp_el2{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C4_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AFSR0_EL3` AArch64 system register (no named fields yet). */
struct afsr0_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static afsr0_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C5_C1_0" : "=r"(value));
    return afsr0_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C5_C1_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AFSR1_EL3` AArch64 system register (no named fields yet). */
struct afsr1_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static afsr1_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C5_C1_1" : "=r"(value));
    return afsr1_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C5_C1_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `ESR_EL3` AArch64 system register (no named fields yet). */
struct esr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static esr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C5_C2_0" : "=r"(value));
    return esr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C5_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `FAR_EL3` AArch64 system register (no named fields yet). */
struct far_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static far_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C6_C0_0" : "=r"(value));
    return far_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C6_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `MAIR_EL3` AArch64 system register (no named fields yet). */
struct mair_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static mair_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C10_C2_0" : "=r"(value));
    return mair_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C10_C2_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `AMAIR_EL3` AArch64 system register (no named fields yet). */
struct amair_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static amair_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C10_C3_0" : "=r"(value));
    return amair_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C10_C3_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `VBAR_EL3` AArch64 system register (no named fields yet). */
struct vbar_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static vbar_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C12_C0_0" : "=r"(value));
    return vbar_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C12_C0_0, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `RVBAR_EL3` AArch64 system register (no named fields yet). */
struct rvbar_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static rvbar_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C12_C0_1" : "=r"(value));
    return rvbar_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C12_C0_1, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

/** @brief Raw accessor for the `RMR_EL3` AArch64 system register (no named fields yet). */
struct rmr_el3 {
  std::uint64_t raw{0};

#if defined(__aarch64__)
  [[nodiscard]] static rmr_el3 read() noexcept {
    std::uint64_t value;
    asm volatile("mrs %0, S3_6_C12_C0_2" : "=r"(value));
    return rmr_el3{value};
  }
  void write() const noexcept { asm volatile("msr S3_6_C12_C0_2, %0" ::"r"(raw) : "memory"); }
#endif // defined(__aarch64__)
};

} // namespace structo::arch::arm64::sysreg_raw
