// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

#pragma once

// std-interop-file: embeds structo_printers.py as asm string-literal data, not C++ code

/** @file gdb_printers.hpp
 * @brief Embeds GDB pretty printers for structo::sync types into the binary.
 *
 * Including this header anywhere in a program (typically once, from the
 * translation unit containing `main`) embeds the full contents of
 * `tools/gdb/structo_printers.py` into a `.debug_gdb_scripts` section via
 * inline assembly. When the resulting binary is loaded in GDB, GDB
 * auto-loads and runs that script, registering pretty printers for every
 * `structo::sync` primitive -- no `source` command, no `<binary>-gdb.py`
 * file, and no `sys.path` setup required.
 *
 * This still requires GDB's `auto-load safe-path` to include the path of
 * the binary containing this section (GDB disables auto-loading from
 * untrusted locations by default); see
 * https://sourceware.org/gdb/onlinedocs/gdb/Auto_002dloading-safe-path.html
 *
 * This file is generated by `tools/gdb/generate_embedded_header.py` from
 * `tools/gdb/structo_printers.py` -- do not hand-edit it. Regenerate it
 * whenever the printer script changes.
 *
 * Embedding costs a copy of the (small) Python source in every
 * translation unit that includes this header for a *distinct* binary;
 * the `"MS"` section flags let the linker fold identical copies within
 * the same binary into one, so including it from multiple translation
 * units of the same program is free.
 *
 * The `.debug_gdb_scripts` mechanism relies on GNU-assembler inline `asm`
 * syntax and is only meaningful to GDB, so this header is a silent no-op
 * -- it defines nothing and emits no section -- on compilers other than
 * Clang/GCC (e.g. MSVC). Guarded on `__clang__`/`__GNUC__` rather than
 * platform, so it also no-ops under `clang-cl`, which defines `_MSC_VER`
 * but not GNU inline-asm syntax in its default mode.
 *
 * This follows the exact same mechanism as reloco's own
 * `reloco/gdb_printers.hpp`; see that header and
 * `docs/gdb-pretty-printers.md` for the full rationale.
 */

#if defined(__clang__) || defined(__GNUC__)

// clang-format off
asm(
    ".pushsection \".debug_gdb_scripts\", \"MS\",@progbits,1\n"
    ".byte 4\n" /* SECTION_SCRIPT_ID_PYTHON_TEXT */
    ".ascii \"structo-pretty-printers.py\\n# SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>\\n\"\n"
    ".ascii \"#\\n# SPDX-License-Identifier: BSD-2-Clause\\n\\n\\\"\\\"\\\"GDB pretty printers for the structo header-only li\"\n"
    ".ascii \"brary.\\n\\nThis module can be used in three interchangeable ways:\\n\\n  1. Sourced directly in a runni\"\n"
    ".ascii \"ng GDB session::\\n\\n         (gdb) source /path/to/structo/tools/gdb/structo_printers.py\\n\\n  2. Aut\"\n"
    ".ascii \"o-loaded for a specific binary by placing a ``<binary>-gdb.py``\\n     next to it (or anywhere on \"\n"
    ".ascii \"GDB's auto-load path) containing::\\n\\n         import sys\\n         sys.path.insert(0, \\\"/path/to/st\"\n"
    ".ascii \"ructo/tools/gdb\\\")\\n         import structo_printers\\n         structo_printers.register_structo_pr\"\n"
    ".ascii \"inters()\\n\\n  3. Embedded directly into the binary's ``.debug_gdb_scripts`` section via\\n     ``inc\"\n"
    ".ascii \"lude/structo/sync/gdb_printers.hpp`` (see that header for\\n     details); GDB then loads and runs\"\n"
    ".ascii \" this exact source automatically\\n     when the binary is loaded, with no external file or path\\n \"\n"
    ".ascii \"    configuration required.\\n\\nIn all three cases the printers are registered against ``objfile`` \"\n"
    ".ascii \"(or the\\nglobal printer list, when there is no current object file) the moment this\\nmodule is loa\"\n"
    ".ascii \"ded -- see the bottom of the file.\\n\\nCoverage is currently limited to ``structo::sync`` (see\\n``do\"\n"
    ".ascii \"cs/gdb-pretty-printers.md`` for the exact list and rationale); it can\\ngrow to other `structo` na\"\n"
    ".ascii \"mespaces later following the same pattern.\\n\\\"\\\"\\\"\\n\\ntry:\\n    import gdb\\n    import gdb.printing\\nexce\"\n"
    ".ascii \"pt ImportError:  # pragma: no cover - only importable inside GDB.\\n    gdb = None\\n\\n\\n_ATOMIC_INT_T\"\n"
    ".ascii \"YPE_BY_SIZE = {1: \\\"unsigned char\\\", 2: \\\"unsigned short\\\", 4: \\\"unsigned int\\\", 8: \\\"unsigned long\\\"}\\n\\n\"\n"
    ".ascii \"\\ndef _read_atomic(val):\\n    \\\"\\\"\\\"Reads a `std::atomic<T>`'s value directly from memory, bypassing\\n\"\n"
    ".ascii \"    library-specific internal field layouts entirely.\\n\\n    libstdc++ alone uses at least three d\"\n"
    ".ascii \"ifferent internal shapes\\n    depending on `T` and library version (`_M_i` directly via an\\n    an\"\n"
    ".ascii \"onymous `__atomic_base<T>` base, nested under a named `_M_base`/\\n    `_M_b` member, ...), and li\"\n"
    ".ascii \"bc++ uses yet another (`__a_`/\\n    `__a_value`) -- enumerating and walking all of them is fragil\"\n"
    ".ascii \"e and\\n    guaranteed to miss a future layout. Every mainstream implementation\\n    (libstdc++, li\"\n"
    ".ascii \"bc++, MSVC) instead lays out a lock-free `atomic<T>`\\n    with no padding before `T`'s own bytes \"\n"
    ".ascii \"(required for\\n    `atomic<T>::is_lock_free()` interop with plain `T` in practice, even\\n    thoug\"\n"
    ".ascii \"h the standard itself doesn't mandate it), so reinterpreting the\\n    whole object's storage as a\"\n"
    ".ascii \" plain unsigned integer of the same width\\n    -- via a raw pointer cast against its address, nev\"\n"
    ".ascii \"er by indexing a\\n    named field -- reads the same value every one of those layouts would,\\n    w\"\n"
    ".ascii \"ithout caring which one is actually in play.\\n    \\\"\\\"\\\"\\n    try:\\n        size = int(val.type.sizeof\"\n"
    ".ascii \")\\n        addr = val.address\\n        if addr is None:\\n            return None\\n        type_name \"\n"
    ".ascii \"= _ATOMIC_INT_TYPE_BY_SIZE.get(size)\\n        if type_name is None:\\n            return None\\n     \"\n"
    ".ascii \"   return int(addr.cast(gdb.lookup_type(type_name).pointer()).dereference())\\n    except gdb.erro\"\n"
    ".ascii \"r:\\n        return None\\n\\n\\ndef _format_owner(owner):\\n    \\\"\\\"\\\"Renders a raw `uintptr_t` owner stamp \"\n"
    ".ascii \"as `0 (unlocked)` or a hex address.\\\"\\\"\\\"\\n    if owner == 0:\\n        return \\\"0 (unlocked)\\\"\\n    retu\"\n"
    ".ascii \"rn \\\"0x%x\\\" % owner\\n\\n\\nclass StructoKernelSpinLockPrinter:\\n    \\\"\\\"\\\"Pretty printer for `structo::sync\"\n"
    ".ascii \"::kernel_spin_lock<Traits>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to\"\n"
    ".ascii \"_string(self):\\n        owner = _read_atomic(self.val[\\\"owner_\\\"])\\n        if owner is None:\\n      \"\n"
    ".ascii \"      return \\\"structo::sync::kernel_spin_lock [owner unreadable]\\\"\\n        if owner == 0:\\n       \"\n"
    ".ascii \"     return \\\"structo::sync::kernel_spin_lock [unlocked]\\\"\\n        return \\\"structo::sync::kernel_s\"\n"
    ".ascii \"pin_lock [locked by owner=%s]\\\" % _format_owner(owner)\\n\\n\\nclass StructoTicketSpinLockPrinter:\\n    \"\n"
    ".ascii \"\\\"\\\"\\\"Pretty printer for `structo::sync::ticket_spin_lock<Traits>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val)\"\n"
    ".ascii \":\\n        self.val = val\\n\\n    def to_string(self):\\n        next_ticket = _read_atomic(self.val[\\\"\"\n"
    ".ascii \"next_ticket_\\\"])\\n        now_serving = _read_atomic(self.val[\\\"now_serving_\\\"])\\n        owner = _re\"\n"
    ".ascii \"ad_atomic(self.val[\\\"owner_\\\"])\\n        if next_ticket is None or now_serving is None or owner is \"\n"
    ".ascii \"None:\\n            return \\\"structo::sync::ticket_spin_lock [state unreadable]\\\"\\n        waiting = \"\n"
    ".ascii \"max(0, next_ticket - now_serving - (1 if owner != 0 else 0))\\n        state = \\\"unlocked\\\" if owner\"\n"
    ".ascii \" == 0 else \\\"locked by owner=%s\\\" % _format_owner(owner)\\n        return \\\"structo::sync::ticket_spi\"\n"
    ".ascii \"n_lock [%s, now_serving=%d, next_ticket=%d, %d waiting]\\\" % (\\n            state,\\n            now_\"\n"
    ".ascii \"serving,\\n            next_ticket,\\n            waiting,\\n        )\\n\\n\\nclass StructoQueueSpinLockPri\"\n"
    ".ascii \"nter:\\n    \\\"\\\"\\\"Pretty printer for `structo::sync::queue_spin_lock<Traits>`.\\\"\\\"\\\"\\n\\n    def __init__(s\"\n"
    ".ascii \"elf, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        tail = _read_atomic(self.val\"\n"
    ".ascii \"[\\\"tail_\\\"])\\n        owner = _read_atomic(self.val[\\\"owner_\\\"])\\n        if tail is None or owner is \"\n"
    ".ascii \"None:\\n            return \\\"structo::sync::queue_spin_lock [state unreadable]\\\"\\n        if owner ==\"\n"
    ".ascii \" 0:\\n            return \\\"structo::sync::queue_spin_lock [unlocked]\\\"\\n        tail_desc = \\\"none\\\" if\"\n"
    ".ascii \" tail == 0 else \\\"0x%x\\\" % tail\\n        return \\\"structo::sync::queue_spin_lock [locked by owner=%s\"\n"
    ".ascii \", tail=%s]\\\" % (_format_owner(owner), tail_desc)\\n\\n\\nclass StructoQueueSpinLockNodePrinter:\\n    \\\"\\\"\\\"\"\n"
    ".ascii \"Pretty printer for `structo::sync::queue_spin_lock<Traits>::node`.\\\"\\\"\\\"\\n\\n    def __init__(self, va\"\n"
    ".ascii \"l):\\n        self.val = val\\n\\n    def to_string(self):\\n        waiting = _read_atomic(self.val[\\\"wa\"\n"
    ".ascii \"iting_\\\"])\\n        next_node = _read_atomic(self.val[\\\"next_\\\"])\\n        if waiting is None or next\"\n"
    ".ascii \"_node is None:\\n            return \\\"structo::sync::queue_spin_lock::node [state unreadable]\\\"\\n    \"\n"
    ".ascii \"    status = \\\"waiting\\\" if waiting else (\\\"linked\\\" if next_node != 0 else \\\"idle\\\")\\n        return \\\"\"\n"
    ".ascii \"structo::sync::queue_spin_lock::node [%s, next=%s]\\\" % (\\n            status,\\n            \\\"none\\\" i\"\n"
    ".ascii \"f next_node == 0 else \\\"0x%x\\\" % next_node,\\n        )\\n\\n\\ndef _decode_rw_state(state):\\n    \\\"\\\"\\\"Shared\"\n"
    ".ascii \" bit layout for `rw_spin_lock`/`queue_rw_spin_lock`'s `state_` word.\\n\\n    bit 31 `writer_bit`, b\"\n"
    ".ascii \"it 30 `writer_waiting_bit`, bits 0-29 `reader_mask`;\\n    see either header's top-level docs for \"\n"
    ".ascii \"the full invariants.\\n    \\\"\\\"\\\"\\n    writer_bit = 0x8000_0000\\n    writer_waiting_bit = 0x4000_0000\\n \"\n"
    ".ascii \"   reader_mask = 0x3FFF_FFFF\\n    return {\\n        \\\"write_locked\\\": (state & writer_bit) != 0,\\n   \"\n"
    ".ascii \"     \\\"writer_waiting\\\": (state & writer_waiting_bit) != 0,\\n        \\\"readers\\\": state & reader_mask\"\n"
    ".ascii \",\\n    }\\n\\n\\ndef _rw_state_to_string(type_name, state, owner):\\n    decoded = _decode_rw_state(state\"\n"
    ".ascii \")\\n    if decoded[\\\"write_locked\\\"]:\\n        body = \\\"write-locked by owner=%s\\\" % _format_owner(owne\"\n"
    ".ascii \"r)\\n    elif decoded[\\\"readers\\\"] != 0:\\n        body = \\\"read-locked by %d reader(s)\\\" % decoded[\\\"rea\"\n"
    ".ascii \"ders\\\"]\\n    else:\\n        body = \\\"unlocked\\\"\\n    if decoded[\\\"writer_waiting\\\"]:\\n        body += \\\", \"\n"
    ".ascii \"writer waiting\\\"\\n    return \\\"%s [%s]\\\" % (type_name, body)\\n\\n\\nclass StructoRwSpinLockPrinter:\\n    \\\"\"\n"
    ".ascii \"\\\"\\\"Pretty printer for `structo::sync::rw_spin_lock<Traits>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n   \"\n"
    ".ascii \"     self.val = val\\n\\n    def to_string(self):\\n        state = _read_atomic(self.val[\\\"state_\\\"])\\n \"\n"
    ".ascii \"       owner = _read_atomic(self.val[\\\"owner_\\\"])\\n        if state is None or owner is None:\\n     \"\n"
    ".ascii \"       return \\\"structo::sync::rw_spin_lock [state unreadable]\\\"\\n        return _rw_state_to_strin\"\n"
    ".ascii \"g(\\\"structo::sync::rw_spin_lock\\\", state, owner)\\n\\n\\nclass StructoQueueRwSpinLockPrinter:\\n    \\\"\\\"\\\"Pre\"\n"
    ".ascii \"tty printer for `structo::sync::queue_rw_spin_lock<Traits>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n  \"\n"
    ".ascii \"      self.val = val\\n\\n    def to_string(self):\\n        state = _read_atomic(self.val[\\\"state_\\\"])\\n\"\n"
    ".ascii \"        owner = _read_atomic(self.val[\\\"owner_\\\"])\\n        if state is None or owner is None:\\n    \"\n"
    ".ascii \"        return \\\"structo::sync::queue_rw_spin_lock [state unreadable]\\\"\\n        return _rw_state_t\"\n"
    ".ascii \"o_string(\\\"structo::sync::queue_rw_spin_lock\\\", state, owner)\\n\\n    def children(self):\\n        yie\"\n"
    ".ascii \"ld (\\\"writer_queue_\\\", self.val[\\\"writer_queue_\\\"])\\n\\n\\nclass StructoBackoffPrinter:\\n    \\\"\\\"\\\"Pretty pri\"\n"
    ".ascii \"nter for `structo::sync::backoff`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    \"\n"
    ".ascii \"def to_string(self):\\n        initial = int(self.val[\\\"initial_spins_\\\"])\\n        maxs = int(self.v\"\n"
    ".ascii \"al[\\\"max_spins_\\\"])\\n        current = int(self.val[\\\"spins_\\\"])\\n        return \\\"structo::sync::backo\"\n"
    ".ascii \"ff [spins=%d, initial=%d, max=%d]\\\" % (current, initial, maxs)\\n\\n\\nclass StructoSoftlockDetectorPri\"\n"
    ".ascii \"nter:\\n    \\\"\\\"\\\"Pretty printer for `structo::sync::softlock_detector`.\\\"\\\"\\\"\\n\\n    def __init__(self, v\"\n"
    ".ascii \"al):\\n        self.val = val\\n\\n    def to_string(self):\\n        count = int(self.val[\\\"count_\\\"])\\n  \"\n"
    ".ascii \"      limit = int(self.val[\\\"limit_\\\"])\\n        return \\\"structo::sync::softlock_detector [count=%d\"\n"
    ".ascii \" / limit=%d]\\\" % (count, limit)\\n\\n\\nclass StructoPreemptionGuardPrinter:\\n    \\\"\\\"\\\"Pretty printer for \"\n"
    ".ascii \"`structo::sync::preemption_guard<Traits>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = v\"\n"
    ".ascii \"al\\n\\n    def to_string(self):\\n        armed = bool(self.val[\\\"m_armed\\\"])\\n        return \\\"structo::\"\n"
    ".ascii \"sync::preemption_guard [%s]\\\" % (\\\"armed (preemption disabled)\\\" if armed else \\\"disarmed\\\")\\n\\n\\nclass \"\n"
    ".ascii \"StructoIrqGuardPrinter:\\n    \\\"\\\"\\\"Pretty printer for `structo::sync::irq_guard<Traits>`.\\\"\\\"\\\"\\n\\n    de\"\n"
    ".ascii \"f __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        armed = bool(sel\"\n"
    ".ascii \"f.val[\\\"m_armed\\\"])\\n        flags = int(self.val[\\\"m_flags\\\"])\\n        if not armed:\\n            ret\"\n"
    ".ascii \"urn \\\"structo::sync::irq_guard [disarmed]\\\"\\n        return \\\"structo::sync::irq_guard [armed, saved\"\n"
    ".ascii \"_flags=0x%x]\\\" % flags\\n\\n\\nclass StructoSpinlockEntryGuardPrinter:\\n    \\\"\\\"\\\"Pretty printer for `struc\"\n"
    ".ascii \"to::sync::spinlock_entry_guard<Traits>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\"\n"
    ".ascii \"\\n\\n    def to_string(self):\\n        armed = bool(self.val[\\\"m_armed\\\"])\\n        return \\\"structo::sy\"\n"
    ".ascii \"nc::spinlock_entry_guard [%s]\\\" % (\\\"armed (entered)\\\" if armed else \\\"disarmed\\\")\\n\\n\\nclass StructoCor\"\n"
    ".ascii \"ePinGuardPrinter:\\n    \\\"\\\"\\\"Pretty printer for `structo::sync::core_pin_guard<Traits>`.\\\"\\\"\\\"\\n\\n    def\"\n"
    ".ascii \" __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        armed = bool(self\"\n"
    ".ascii \".val[\\\"m_armed\\\"])\\n        if not armed:\\n            return \\\"structo::sync::core_pin_guard [disarm\"\n"
    ".ascii \"ed]\\\"\\n        return \\\"structo::sync::core_pin_guard [armed, pinned_cpu=%s]\\\" % str(self.val[\\\"m_cpu\"\n"
    ".ascii \"\\\"])\\n\\n\\ndef _build_pretty_printer():\\n    pp = gdb.printing.RegexpCollectionPrettyPrinter(\\\"structo\\\"\"\n"
    ".ascii \")\\n    pp.add_printer(\\\"structo::sync::kernel_spin_lock\\\", r\\\"^structo::sync::kernel_spin_lock<.*>$\\\"\"\n"
    ".ascii \", StructoKernelSpinLockPrinter)\\n    pp.add_printer(\\\"structo::sync::ticket_spin_lock\\\", r\\\"^structo\"\n"
    ".ascii \"::sync::ticket_spin_lock<.*>$\\\", StructoTicketSpinLockPrinter)\\n    pp.add_printer(\\\"structo::sync:\"\n"
    ".ascii \":queue_spin_lock\\\", r\\\"^structo::sync::queue_spin_lock<.*>$\\\", StructoQueueSpinLockPrinter)\\n    pp.\"\n"
    ".ascii \"add_printer(\\n        \\\"structo::sync::queue_spin_lock::node\\\",\\n        r\\\"^structo::sync::queue_spi\"\n"
    ".ascii \"n_lock<.*>::node$\\\",\\n        StructoQueueSpinLockNodePrinter,\\n    )\\n    pp.add_printer(\\\"structo::\"\n"
    ".ascii \"sync::rw_spin_lock\\\", r\\\"^structo::sync::rw_spin_lock<.*>$\\\", StructoRwSpinLockPrinter)\\n    pp.add_\"\n"
    ".ascii \"printer(\\n        \\\"structo::sync::queue_rw_spin_lock\\\", r\\\"^structo::sync::queue_rw_spin_lock<.*>$\\\"\"\n"
    ".ascii \", StructoQueueRwSpinLockPrinter\\n    )\\n    pp.add_printer(\\\"structo::sync::backoff\\\", r\\\"^structo::s\"\n"
    ".ascii \"ync::backoff$\\\", StructoBackoffPrinter)\\n    pp.add_printer(\\\"structo::sync::softlock_detector\\\", r\\\"\"\n"
    ".ascii \"^structo::sync::softlock_detector$\\\", StructoSoftlockDetectorPrinter)\\n    pp.add_printer(\\\"structo\"\n"
    ".ascii \"::sync::preemption_guard\\\", r\\\"^structo::sync::preemption_guard<.*>$\\\", StructoPreemptionGuardPrint\"\n"
    ".ascii \"er)\\n    pp.add_printer(\\\"structo::sync::irq_guard\\\", r\\\"^structo::sync::irq_guard<.*>$\\\", StructoIrq\"\n"
    ".ascii \"GuardPrinter)\\n    pp.add_printer(\\n        \\\"structo::sync::spinlock_entry_guard\\\", r\\\"^structo::syn\"\n"
    ".ascii \"c::spinlock_entry_guard<.*>$\\\", StructoSpinlockEntryGuardPrinter\\n    )\\n    pp.add_printer(\\\"struct\"\n"
    ".ascii \"o::sync::core_pin_guard\\\", r\\\"^structo::sync::core_pin_guard<.*>$\\\", StructoCorePinGuardPrinter)\\n  \"\n"
    ".ascii \"  return pp\\n\\n\\ndef register_structo_printers(objfile=None):\\n    \\\"\\\"\\\"Registers the structo pretty p\"\n"
    ".ascii \"rinters with GDB.\\n\\n    Idempotent: re-registering (e.g. because this module was sourced twice,\\n \"\n"
    ".ascii \"   or embedded in several object files) simply replaces the previous\\n    registration under the \"\n"
    ".ascii \"same name.\\n    \\\"\\\"\\\"\\n    if gdb is None:\\n        return\\n\\n    target = objfile if objfile is not No\"\n"
    ".ascii \"ne else gdb\\n    gdb.printing.register_pretty_printer(target, _build_pretty_printer(), replace=Tr\"\n"
    ".ascii \"ue)\\n\\n\\nif gdb is not None:\\n    register_structo_printers(gdb.current_objfile())\\n\"\n"
    ".byte 0\n"
    ".popsection\n"
);
// clang-format on

#endif // defined(__clang__) || defined(__GNUC__)
