// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

// Generated by scripts/sysregs/gen_sysreg_headers.py from
// scripts/sysregs/arm.yaml -- do not edit by hand.
//
// Each struct below is a thin, bit-field-free wrapper around one raw system
// register value plus, when compiling for a matching target architecture,
// `read()`/`write()` accessors implemented with inline asm. No named
// bit-field accessors are generated yet (`fields` is empty for every
// register in the source YAML); re-running the generator after that YAML
// gains field data will add them here without otherwise changing this file.

#pragma once

#include <cstdint>

namespace structo::arch::arm::sysreg_raw {

/** @brief Raw accessor for the AArch32 `DBGDIDR` coprocessor register (no named fields yet). */
struct dbgdidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgdidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c0, c0, 0" : "=r"(value));
    return dbgdidr{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c0, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DBGDSCREXT_V6` coprocessor register (no named fields yet). */
struct dbgdscrext_v6 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgdscrext_v6 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c0, c1, 0" : "=r"(value));
    return dbgdscrext_v6{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c0, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DBGDSCREXT_V7` coprocessor register (no named fields yet). */
struct dbgdscrext_v7 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgdscrext_v7 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c0, c2, 2" : "=r"(value));
    return dbgdscrext_v7{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c0, c2, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DBGVCR` coprocessor register (no named fields yet). */
struct dbgvcr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgvcr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c0, c7, 0" : "=r"(value));
    return dbgvcr{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c0, c7, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DBGOSLAR` coprocessor register (no named fields yet). */
struct dbgoslar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgoslar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c1, c0, 4" : "=r"(value));
    return dbgoslar{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c1, c0, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DBGOSLSR` coprocessor register (no named fields yet). */
struct dbgoslsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgoslsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c1, c1, 4" : "=r"(value));
    return dbgoslsr{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c1, c1, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DBGOSDLR` coprocessor register (no named fields yet). */
struct dbgosdlr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgosdlr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c1, c3, 4" : "=r"(value));
    return dbgosdlr{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c1, c3, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DBGPRSR` coprocessor register (no named fields yet). */
struct dbgprsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dbgprsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p14, 0, %0, c1, c5, 4" : "=r"(value));
    return dbgprsr{value};
  }
  void write() const noexcept { asm volatile("mcr p14, 0, %0, c1, c5, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `MIDR` coprocessor register (no named fields yet). */
struct midr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static midr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c0, 0" : "=r"(value));
    return midr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CTR` coprocessor register (no named fields yet). */
struct ctr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ctr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c0, 1" : "=r"(value));
    return ctr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c0, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TCMTR` coprocessor register (no named fields yet). */
struct tcmtr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tcmtr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c0, 2" : "=r"(value));
    return tcmtr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBTR` coprocessor register (no named fields yet). */
struct tlbtr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbtr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c0, 3" : "=r"(value));
    return tlbtr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c0, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `MPIDR` coprocessor register (no named fields yet). */
struct mpidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static mpidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c0, 5" : "=r"(value));
    return mpidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c0, 5" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `REVIDR` coprocessor register (no named fields yet). */
struct revidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static revidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c0, 6" : "=r"(value));
    return revidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c0, 6" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_PFR0` coprocessor register (no named fields yet). */
struct id_pfr0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_pfr0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 0" : "=r"(value));
    return id_pfr0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_PFR1` coprocessor register (no named fields yet). */
struct id_pfr1 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_pfr1 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 1" : "=r"(value));
    return id_pfr1{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_DFR0` coprocessor register (no named fields yet). */
struct id_dfr0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_dfr0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 2" : "=r"(value));
    return id_dfr0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_AFR0` coprocessor register (no named fields yet). */
struct id_afr0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_afr0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 3" : "=r"(value));
    return id_afr0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_MMFR0` coprocessor register (no named fields yet). */
struct id_mmfr0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_mmfr0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 4" : "=r"(value));
    return id_mmfr0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_MMFR1` coprocessor register (no named fields yet). */
struct id_mmfr1 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_mmfr1 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 5" : "=r"(value));
    return id_mmfr1{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 5" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_MMFR2` coprocessor register (no named fields yet). */
struct id_mmfr2 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_mmfr2 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 6" : "=r"(value));
    return id_mmfr2{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 6" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_MMFR3` coprocessor register (no named fields yet). */
struct id_mmfr3 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_mmfr3 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c1, 7" : "=r"(value));
    return id_mmfr3{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c1, 7" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_ISAR0` coprocessor register (no named fields yet). */
struct id_isar0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_isar0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c2, 0" : "=r"(value));
    return id_isar0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c2, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_ISAR1` coprocessor register (no named fields yet). */
struct id_isar1 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_isar1 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c2, 1" : "=r"(value));
    return id_isar1{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c2, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_ISAR2` coprocessor register (no named fields yet). */
struct id_isar2 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_isar2 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c2, 2" : "=r"(value));
    return id_isar2{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c2, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_ISAR3` coprocessor register (no named fields yet). */
struct id_isar3 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_isar3 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c2, 3" : "=r"(value));
    return id_isar3{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c2, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_ISAR4` coprocessor register (no named fields yet). */
struct id_isar4 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_isar4 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c2, 4" : "=r"(value));
    return id_isar4{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c2, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ID_ISAR5` coprocessor register (no named fields yet). */
struct id_isar5 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static id_isar5 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c0, c2, 5" : "=r"(value));
    return id_isar5{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c0, c2, 5" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CCSIDR` coprocessor register (no named fields yet). */
struct ccsidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ccsidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 1, %0, c0, c0, 0" : "=r"(value));
    return ccsidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 1, %0, c0, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CLIDR` coprocessor register (no named fields yet). */
struct clidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static clidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 1, %0, c0, c0, 1" : "=r"(value));
    return clidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 1, %0, c0, c0, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `AIDR` coprocessor register (no named fields yet). */
struct aidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static aidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 1, %0, c0, c0, 7" : "=r"(value));
    return aidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 1, %0, c0, c0, 7" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CSSELR` coprocessor register (no named fields yet). */
struct csselr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static csselr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 2, %0, c0, c0, 0" : "=r"(value));
    return csselr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 2, %0, c0, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `VPIDR` coprocessor register (no named fields yet). */
struct vpidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static vpidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c0, c0, 0" : "=r"(value));
    return vpidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c0, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `VMPIDR` coprocessor register (no named fields yet). */
struct vmpidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static vmpidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c0, c0, 5" : "=r"(value));
    return vmpidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c0, c0, 5" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `SCTLR` coprocessor register (no named fields yet). */
struct sctlr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static sctlr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c1, c0, 0" : "=r"(value));
    return sctlr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c1, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ACTLR` coprocessor register (no named fields yet). */
struct actlr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static actlr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c1, c0, 1" : "=r"(value));
    return actlr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c1, c0, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CPACR` coprocessor register (no named fields yet). */
struct cpacr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cpacr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c1, c0, 2" : "=r"(value));
    return cpacr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c1, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `SCR` coprocessor register (no named fields yet). */
struct scr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static scr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c1, c1, 0" : "=r"(value));
    return scr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c1, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `SDER` coprocessor register (no named fields yet). */
struct sder {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static sder read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c1, c1, 1" : "=r"(value));
    return sder{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c1, c1, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `NSACR` coprocessor register (no named fields yet). */
struct nsacr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static nsacr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c1, c1, 2" : "=r"(value));
    return nsacr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c1, c1, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HSCTLR` coprocessor register (no named fields yet). */
struct hsctlr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hsctlr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c1, c0, 0" : "=r"(value));
    return hsctlr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c1, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HCR` coprocessor register (no named fields yet). */
struct hcr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hcr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c1, c1, 0" : "=r"(value));
    return hcr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c1, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HDCR` coprocessor register (no named fields yet). */
struct hdcr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hdcr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c1, c1, 1" : "=r"(value));
    return hdcr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c1, c1, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HCPTR` coprocessor register (no named fields yet). */
struct hcptr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hcptr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c1, c1, 2" : "=r"(value));
    return hcptr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c1, c1, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HSTR` coprocessor register (no named fields yet). */
struct hstr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hstr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c1, c1, 3" : "=r"(value));
    return hstr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c1, c1, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TTBR0` coprocessor register (no named fields yet). */
struct ttbr0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ttbr0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c2, c0, 0" : "=r"(value));
    return ttbr0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c2, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TTBR1` coprocessor register (no named fields yet). */
struct ttbr1 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ttbr1 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c2, c0, 1" : "=r"(value));
    return ttbr1{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c2, c0, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TTBCR` coprocessor register (no named fields yet). */
struct ttbcr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ttbcr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c2, c0, 2" : "=r"(value));
    return ttbcr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c2, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HTCR` coprocessor register (no named fields yet). */
struct htcr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static htcr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c2, c0, 2" : "=r"(value));
    return htcr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c2, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `VTCR` coprocessor register (no named fields yet). */
struct vtcr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static vtcr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c2, c1, 2" : "=r"(value));
    return vtcr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c2, c1, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DACR` coprocessor register (no named fields yet). */
struct dacr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dacr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c3, c0, 0" : "=r"(value));
    return dacr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c3, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DFSR` coprocessor register (no named fields yet). */
struct dfsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dfsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c5, c0, 0" : "=r"(value));
    return dfsr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c5, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HSR` coprocessor register (no named fields yet). */
struct hsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c5, c2, 0" : "=r"(value));
    return hsr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c5, c2, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `IFSR` coprocessor register (no named fields yet). */
struct ifsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ifsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c5, c0, 1" : "=r"(value));
    return ifsr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c5, c0, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ADFSR` coprocessor register (no named fields yet). */
struct adfsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static adfsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c5, c1, 0" : "=r"(value));
    return adfsr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c5, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `AIFSR` coprocessor register (no named fields yet). */
struct aifsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static aifsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c5, c1, 1" : "=r"(value));
    return aifsr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c5, c1, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DFAR` coprocessor register (no named fields yet). */
struct dfar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dfar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c6, c0, 0" : "=r"(value));
    return dfar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c6, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HDFAR` coprocessor register (no named fields yet). */
struct hdfar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hdfar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c6, c0, 0" : "=r"(value));
    return hdfar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c6, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HIFAR` coprocessor register (no named fields yet). */
struct hifar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hifar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c6, c0, 2" : "=r"(value));
    return hifar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c6, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HPFAR` coprocessor register (no named fields yet). */
struct hpfar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hpfar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c6, c0, 4" : "=r"(value));
    return hpfar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c6, c0, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `IFAR` coprocessor register (no named fields yet). */
struct ifar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ifar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c6, c0, 2" : "=r"(value));
    return ifar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c6, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PAR` coprocessor register (no named fields yet). */
struct par {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static par read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c4, 0" : "=r"(value));
    return par{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c4, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ICIMVAU` coprocessor register (no named fields yet). */
struct icimvau {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static icimvau read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c5, 1" : "=r"(value));
    return icimvau{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c5, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DCIMVAC` coprocessor register (no named fields yet). */
struct dcimvac {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dcimvac read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c6, 1" : "=r"(value));
    return dcimvac{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c6, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DCISW` coprocessor register (no named fields yet). */
struct dcisw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dcisw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c6, 2" : "=r"(value));
    return dcisw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c6, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS1_CPR` coprocessor register (no named fields yet). */
struct ats1_cpr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats1_cpr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 0" : "=r"(value));
    return ats1_cpr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS1_CPW` coprocessor register (no named fields yet). */
struct ats1_cpw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats1_cpw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 1" : "=r"(value));
    return ats1_cpw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS1_CUR` coprocessor register (no named fields yet). */
struct ats1_cur {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats1_cur read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 2" : "=r"(value));
    return ats1_cur{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS1_CUW` coprocessor register (no named fields yet). */
struct ats1_cuw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats1_cuw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 3" : "=r"(value));
    return ats1_cuw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS12_NSOPR` coprocessor register (no named fields yet). */
struct ats12_nsopr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats12_nsopr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 4" : "=r"(value));
    return ats12_nsopr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS12_NSOPW` coprocessor register (no named fields yet). */
struct ats12_nsopw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats12_nsopw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 5" : "=r"(value));
    return ats12_nsopw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 5" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS12_NSOUR` coprocessor register (no named fields yet). */
struct ats12_nsour {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats12_nsour read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 6" : "=r"(value));
    return ats12_nsour{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 6" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ATS12_NSOUW` coprocessor register (no named fields yet). */
struct ats12_nsouw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static ats12_nsouw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c8, 7" : "=r"(value));
    return ats12_nsouw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c8, 7" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DCCMVAC` coprocessor register (no named fields yet). */
struct dccmvac {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dccmvac read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c10, 1" : "=r"(value));
    return dccmvac{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c10, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DCCSW` coprocessor register (no named fields yet). */
struct dccsw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dccsw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c10, 2" : "=r"(value));
    return dccsw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c10, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DCCMVAU` coprocessor register (no named fields yet). */
struct dccmvau {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dccmvau read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c11, 1" : "=r"(value));
    return dccmvau{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c11, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DCCIMVAC` coprocessor register (no named fields yet). */
struct dccimvac {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dccimvac read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c14, 1" : "=r"(value));
    return dccimvac{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c14, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `DCCISW` coprocessor register (no named fields yet). */
struct dccisw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static dccisw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c7, c14, 2" : "=r"(value));
    return dccisw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c7, c14, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBIMVAIS` coprocessor register (no named fields yet). */
struct tlbimvais {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbimvais read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c8, c3, 1" : "=r"(value));
    return tlbimvais{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c8, c3, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBIASIDIS` coprocessor register (no named fields yet). */
struct tlbiasidis {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbiasidis read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c8, c3, 2" : "=r"(value));
    return tlbiasidis{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c8, c3, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBIMVAAIS` coprocessor register (no named fields yet). */
struct tlbimvaais {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbimvaais read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c8, c3, 3" : "=r"(value));
    return tlbimvaais{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c8, c3, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBIMVA` coprocessor register (no named fields yet). */
struct tlbimva {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbimva read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c8, c7, 1" : "=r"(value));
    return tlbimva{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c8, c7, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBIASID` coprocessor register (no named fields yet). */
struct tlbiasid {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbiasid read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c8, c7, 2" : "=r"(value));
    return tlbiasid{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c8, c7, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBIALLH` coprocessor register (no named fields yet). */
struct tlbiallh {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbiallh read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c8, c7, 0" : "=r"(value));
    return tlbiallh{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c8, c7, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TLBIMVAA` coprocessor register (no named fields yet). */
struct tlbimvaa {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tlbimvaa read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c8, c7, 3" : "=r"(value));
    return tlbimvaa{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c8, c7, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `L2_CTLR` coprocessor register (no named fields yet). */
struct l2_ctlr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static l2_ctlr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 1, %0, c9, c0, 2" : "=r"(value));
    return l2_ctlr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 1, %0, c9, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMCR` coprocessor register (no named fields yet). */
struct pmcr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmcr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c12, 0" : "=r"(value));
    return pmcr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c12, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMCNTENSET` coprocessor register (no named fields yet). */
struct pmcntenset {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmcntenset read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c12, 1" : "=r"(value));
    return pmcntenset{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c12, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMCNTENCLR` coprocessor register (no named fields yet). */
struct pmcntenclr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmcntenclr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c12, 2" : "=r"(value));
    return pmcntenclr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c12, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMOVSR` coprocessor register (no named fields yet). */
struct pmovsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmovsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c12, 3" : "=r"(value));
    return pmovsr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c12, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMSWINC` coprocessor register (no named fields yet). */
struct pmswinc {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmswinc read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c12, 4" : "=r"(value));
    return pmswinc{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c12, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMSELR` coprocessor register (no named fields yet). */
struct pmselr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmselr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c12, 5" : "=r"(value));
    return pmselr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c12, 5" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMCCNTR` coprocessor register (no named fields yet). */
struct pmccntr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmccntr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c13, 0" : "=r"(value));
    return pmccntr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c13, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMXEVTYPER` coprocessor register (no named fields yet). */
struct pmxevtyper {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmxevtyper read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c13, 1" : "=r"(value));
    return pmxevtyper{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c13, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMXEVCNTRR` coprocessor register (no named fields yet). */
struct pmxevcntrr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmxevcntrr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c13, 2" : "=r"(value));
    return pmxevcntrr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c13, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMUSERENR` coprocessor register (no named fields yet). */
struct pmuserenr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmuserenr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c14, 0" : "=r"(value));
    return pmuserenr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c14, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMINTENSET` coprocessor register (no named fields yet). */
struct pmintenset {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmintenset read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c14, 1" : "=r"(value));
    return pmintenset{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c14, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PMINTENCLR` coprocessor register (no named fields yet). */
struct pmintenclr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static pmintenclr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c9, c14, 2" : "=r"(value));
    return pmintenclr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c9, c14, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `PRRR` coprocessor register (no named fields yet). */
struct prrr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static prrr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c10, c2, 0" : "=r"(value));
    return prrr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c10, c2, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `MAIR0` coprocessor register (no named fields yet). */
struct mair0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static mair0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c10, c2, 0" : "=r"(value));
    return mair0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c10, c2, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `NMRR` coprocessor register (no named fields yet). */
struct nmrr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static nmrr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c10, c2, 1" : "=r"(value));
    return nmrr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c10, c2, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `MAIR1` coprocessor register (no named fields yet). */
struct mair1 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static mair1 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c10, c2, 1" : "=r"(value));
    return mair1{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c10, c2, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `AMAIR0` coprocessor register (no named fields yet). */
struct amair0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static amair0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c10, c3, 0" : "=r"(value));
    return amair0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c10, c3, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `AMAIR1` coprocessor register (no named fields yet). */
struct amair1 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static amair1 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c10, c3, 1" : "=r"(value));
    return amair1{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c10, c3, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HMAIR0` coprocessor register (no named fields yet). */
struct hmair0 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hmair0 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c10, c2, 0" : "=r"(value));
    return hmair0{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c10, c2, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HMAIR1` coprocessor register (no named fields yet). */
struct hmair1 {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hmair1 read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c10, c2, 1" : "=r"(value));
    return hmair1{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c10, c2, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `VBAR` coprocessor register (no named fields yet). */
struct vbar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static vbar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c12, c0, 0" : "=r"(value));
    return vbar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c12, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `MVBAR` coprocessor register (no named fields yet). */
struct mvbar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static mvbar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c12, c0, 1" : "=r"(value));
    return mvbar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c12, c0, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `ISR` coprocessor register (no named fields yet). */
struct isr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static isr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c12, c1, 0" : "=r"(value));
    return isr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c12, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HVBAR` coprocessor register (no named fields yet). */
struct hvbar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static hvbar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c12, c0, 0" : "=r"(value));
    return hvbar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c12, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `FCSEIDR` coprocessor register (no named fields yet). */
struct fcseidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static fcseidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c13, c0, 0" : "=r"(value));
    return fcseidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c13, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CONTEXTIDR` coprocessor register (no named fields yet). */
struct contextidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static contextidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c13, c0, 1" : "=r"(value));
    return contextidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c13, c0, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TPIDRURW` coprocessor register (no named fields yet). */
struct tpidrurw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tpidrurw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c13, c0, 2" : "=r"(value));
    return tpidrurw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c13, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TPIDRURO` coprocessor register (no named fields yet). */
struct tpidruro {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tpidruro read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c13, c0, 3" : "=r"(value));
    return tpidruro{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c13, c0, 3" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `TPIDRPRW` coprocessor register (no named fields yet). */
struct tpidrprw {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static tpidrprw read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c13, c0, 4" : "=r"(value));
    return tpidrprw{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c13, c0, 4" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `HTPIDR` coprocessor register (no named fields yet). */
struct htpidr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static htpidr read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c13, c0, 2" : "=r"(value));
    return htpidr{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c13, c0, 2" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTFRQ` coprocessor register (no named fields yet). */
struct cntfrq {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cntfrq read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c14, c0, 0" : "=r"(value));
    return cntfrq{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c14, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTKCTL` coprocessor register (no named fields yet). */
struct cntkctl {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cntkctl read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c14, c1, 0" : "=r"(value));
    return cntkctl{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c14, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTP_TVAL` coprocessor register (no named fields yet). */
struct cntp_tval {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cntp_tval read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c14, c2, 0" : "=r"(value));
    return cntp_tval{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c14, c2, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTP_CTL` coprocessor register (no named fields yet). */
struct cntp_ctl {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cntp_ctl read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c14, c2, 1" : "=r"(value));
    return cntp_ctl{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c14, c2, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTV_TVAL` coprocessor register (no named fields yet). */
struct cntv_tval {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cntv_tval read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c14, c3, 0" : "=r"(value));
    return cntv_tval{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c14, c3, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTV_CTL` coprocessor register (no named fields yet). */
struct cntv_ctl {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cntv_ctl read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 0, %0, c14, c3, 1" : "=r"(value));
    return cntv_ctl{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 0, %0, c14, c3, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTHCTL` coprocessor register (no named fields yet). */
struct cnthctl {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cnthctl read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c14, c1, 0" : "=r"(value));
    return cnthctl{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c14, c1, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTHP_TVAL` coprocessor register (no named fields yet). */
struct cnthp_tval {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cnthp_tval read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c14, c2, 0" : "=r"(value));
    return cnthp_tval{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c14, c2, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CNTHP_CTL` coprocessor register (no named fields yet). */
struct cnthp_ctl {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cnthp_ctl read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c14, c2, 1" : "=r"(value));
    return cnthp_ctl{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c14, c2, 1" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CBAR` coprocessor register (no named fields yet). */
struct cbar {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cbar read() noexcept {
    std::uint32_t value;
    asm volatile("mrc p15, 4, %0, c15, c0, 0" : "=r"(value));
    return cbar{value};
  }
  void write() const noexcept { asm volatile("mcr p15, 4, %0, c15, c0, 0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `CPSR` status register (no named fields yet). */
struct cpsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static cpsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrs %0, cpsr" : "=r"(value));
    return cpsr{value};
  }
  void write() const noexcept { asm volatile("msr cpsr_fsxc, %0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

/** @brief Raw accessor for the AArch32 `SPSR` status register (no named fields yet). */
struct spsr {
  std::uint32_t raw{0};

#if defined(__arm__) && !defined(__aarch64__)
  [[nodiscard]] static spsr read() noexcept {
    std::uint32_t value;
    asm volatile("mrs %0, spsr" : "=r"(value));
    return spsr{value};
  }
  void write() const noexcept { asm volatile("msr spsr_fsxc, %0" ::"r"(raw)); }
#endif // defined(__arm__) && !defined(__aarch64__)
};

} // namespace structo::arch::arm::sysreg_raw
